### ISSUE TITLE
write more thorough tests for CLI API

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#104]
this issue is to prevent regressions like #76 from happening

I have a few basic tests in `test/tests/cli.js`, but we could use more! If you are interested in writing some tests it should be pretty self explanatory on how to add more.

In particular there have been some weird bugs around spawning multiple processes (due to the way dat is an rpc client/server to allow multiple instances of itself to share the same leveldb), but all known issues around this have been fixed at this point

for a list of CLI commands that need tests check out the CLI commands whitelist in `cli.js`

**Comment by karissa** [comment]
Closing as it refers to alpha.
