### ISSUE TITLE
Adherence to W3C PROV standard

### ISSUE THREAD

**Issue by augusto-herrmann** [maxogden/dat#11]
The whole process of dealing with data in `dat` should conform to the [PROV](http://www.w3.org/TR/prov-overview/) [1] standard by W3C.
Transformation and syncing in `dat` should conform to the [PROV Data Model](http://www.w3.org/TR/prov-dm/) [2].
Data history should be made exportable into [PROV XML](http://www.w3.org/TR/prov-xml/) [3] and [RDF](http://www.w3.org/TR/prov-o/) [4] formats to enhance interoperability and ease the documentation of provenance metadata.

I think `dat` has the potential to be the essential toool to handle data and at the same time automatically track provenance in a standardized way.

[1] http://www.w3.org/TR/prov-overview/
[2] http://www.w3.org/TR/prov-dm/
[3] http://www.w3.org/TR/prov-xml/
[4] http://www.w3.org/TR/prov-o/

**Comment by karissa** [comment]
Thanks for trying out dat beta and submitting an issue. After a whole year of feedback from the community, we recently published a new version of dat... and it makes this issue obsolete. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
