### ISSUE TITLE
filtered pull

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#112]
we should steal this idea from couchdb:

```
The replication can be filtered by passing the filter parameter to the changes feeds with a function name. This will call a function on each changes. If this function return True, the document will be added to the feed.
```

e.g. when we add #95 there should also be a way to attach a filter to it so you can do e.g. 'replicate all npm modules but only ones written by substack'

**Comment by karissa** [comment]
related to #286

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
