### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by todrobbins** [maxogden/dat#114]
I think it'd be great to have usage examples built into dat. For instance, I like how you can type
```
example(min)
```
in R and it lists usage details for that function:
```
min> require(stats); require(graphics)

min>  min(5:1, pi) #-> one number
[1] 1

min> pmin(5:1, pi) #->  5  numbers
[1] 3.141593 3.141593 3.000000 2.000000 1.000000
```
Maybe it's because I like quick references, but I think this would be nice for the various tools within the dat ecosystem.

Cheers!

**Comment by brianshumate** [comment]
Would adding usage examples to the various `dat <command> --help` output be sufficient to cover this? If so, I think I could help out here.

**Comment by karissa** [comment]
We recently published a new version of dat that makes this issue obsolete. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
