### ISSUE TITLE
pilot dataset/use cases

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#12]
describe and link to datasets that I can use as a way to pilot/test out `dat`!

via @loleg:

- extracting financial data from 26 Swiss cantons and their 2500 administrational units (cities etc) - for instance, over the weekend I hacked on a [command line PDF converter](https://github.com/loleg/open-budget-miner) which I just posted to [Scraperwiki](https://classic.scraperwiki.com/scrapers/kanton_bern_finanzplan/)
- scraping the [national law database](http://www.parlament.ch/ab/frameset/d/n/4909/406105/d_n_4909_406105_406145.htm) into a reasonably parseable format that allows semantic annotation (i.e. NLP + legal ontology) and visualization, one of several ideas for a legal hackday I'm organizing
- collating personal data from participants in an open (as in, the door is ajar) [loyalty program](http://cumulizer.eu/) and packaging it up for social science researchers in a way that the corporates get the oversight they need to not shut us down
- creating an activity feed of the dozens of projects we've started in our [Open Data community](http://ch.okfn.org/), combining [social/site metrics](http://make.opendata.ch/wiki/project:makeopendata) with GitHub, wiki, forum updates
- setting up a grassroots (p2p?) datastore that people can chuck ideas into / collaborate à la (the now defunct) BuzzData, build their APIs against before moving somewhere more stable, basically the idea for [http://datalets.ch](http://datalets.ch/) -- must be easy enough to use to [bring into schools](http://blog.utou.ch/2013/open-data-for-kids/), teach people coding with

others:

- normalize, enrich and export species interaction data through http://eol.org using existing species interaction datasets. Here is the [current workflow](https://github.com/jhpoelen/eol-globi-data/wiki#access-via-flat-files)
- make it easier for election data providers (states, cities) to publish data feeds so they can be consumed by https://votinginfoproject.org/

**Comment by joehand** [comment]
This issue was moved to datproject/discussions#41
