### ISSUE TITLE
Querying by Range

### ISSUE THREAD

**Issue by jason-riddle** [maxogden/dat#123]
Once data has been imported, is there any way to query a range of data?  So if there is a column that has several years between 1960 and 2010, is there a way to specify a range to get information between 1970 and 1975 for example?

**Comment by karissa** [comment]
We recently published a new version of dat that closes this issue. This would be a great feature to have in dat, but right now it's only available in the lower-level hyperdrive API. It's on the todo list, though.

 Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
