### ISSUE TITLE
Community Data

### ISSUE THREAD

**Issue by msenateatplos** [maxogden/dat#13]
The intro text to [wikidata.org](http://wikidata.org/) hits the high-level:
> Wikidata is a free knowledge base that can be read and edited by humans and machines alike. It is for data what Wikimedia Commons is for media files: it centralizes access to and management of structured data, such as interwiki references and statistical information. Wikidata contains data in every language supported by the MediaWiki software.

After some conversations with folks involved with WikiData, I can see its role on the web in a more sensitive light. There is on-going movement ([formal](http://wikimediafoundation.org/wiki/Editor_engagement_experiments) and informal) to address the observable decline in user base (and dwindling conversions of new users to returning editors) to Wikimedia projects, especially [the English Wikipedia](http://en.wikipedia.org/wiki/Wikipedia:Wikipedia_Signpost/2012-09-24/Recent_research).

However, the trajectory of Wikimedia projects is certainly on the rise--its aggregate dataset (semi-structured text and structured-ish data alike) continues to grow. There are **48,794,118** *good* articles and  **20,054,661** images across [200 Wikimedia projects](http://wikistats.wmflabs.org/wikimedias_html.php).

WikiData exemplifies another transition for the community-driven knowledge project that sprouted from the English language Wikipedia. The future of the sum of all human knowledge is human- and programmatically-accessible, community-managed, and open-licensed.

The opportunity of WikiData is a basic, but large layer for data that *matters* to people.

The community around Wikipedia grew out of natural inclinations and interests. As a result, the majority of editors who generate this content are not nearly as diverse a group as we should require. This produces errors of omission, limited views and perspective, and a propagation of some elements of some cultures, but not many other elements, and not many other entire cultures. For instance, there is an English-centric focus of Wikimedia work, and the gender imbalance both in coverage and editors is clearly unacceptable.

We have a chance to be mindful of the prospect of WikiData, and I think even embrace it, plan to work with it, to integrate, and make read-write relationships. We must do this, more than anything, because there are few alternatives for constructing and maintaining data that prioritize community values and common good.

Perhaps dat does not necessarily merge, even at its beginning, with WikiData, but I think the example and its principles should be some good food for thought!

**Comment by karissa** [comment]
Love Wikidata. We'd love to make wikidata datasets `dat clone`-able. If you have any insight into who might want to bottomline that task, I'd love to help..

**Comment by joehand** [comment]
This issue was moved to datproject/discussions#42
