### ISSUE TITLE
Interesting Visualizations Frameworks

### ISSUE THREAD

**Issue by jbenet** [maxogden/dat#133]
Hey Watchers! 

It would be very useful for us to collect interesting visualization tools that could be run on top of [dat-editor](https://github.com/maxogden/dat-editor). What we're considering is having a way to load special dat-viz modules (which understand dat) directly from npm, like @maxogden's [requirebin](http://requirebin.com). These modules would translate the data to something the visualization tool can use, and render the visualization. That way, people could publish some module that applied some nifty data viz to specific types of data, and you could run it directly from the frontend ui of whatever dat-editor you're looking at.

So, if you have really cool visualizations of specific data types that you'd love to see on your dat data, post it here. 

I'll get rid of the simple examples:

- simple charts with http://morrisjs.github.io/morris.js/
- all sorts of things with d3.js -- but made easy. i.e. modules should do one thing, but might use d3 to do it, e.g. dat-viz-histogram
- time series with
  - http://fastly.github.io/epoch/
  - http://code.shutterstock.com/rickshaw/
- networks with http://sigmajs.org/
- heatmaps with http://www.patrick-wied.at/static/heatmapjs/#
- http://dygraphs.com/

**Comment by shotlom** [comment]
What's happening with this idea? Has there been any movement since 2014?

**Comment by karissa** [comment]
@shotlom i think i'm going to close this as it refers to the alpha, and anything developed would be a standalone module that interfaces with dat.
