### ISSUE TITLE
Linting csv files in options?

### ISSUE THREAD

**Issue by chilijung** [maxogden/dat#136]
Due to csv files is using in various kind of fields, implement csvlint might be helpful for some cases, just a thought.
https://github.com/chilijung/csvlint.js

How do you think? Any ideas?

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat. I think this would be best handled by an external module.  Would you mind trying out the new dat with npm install -g dat? You can read about the new dat announcement on the website and how it works in the docs.
