### ISSUE TITLE
rolling hashes/blob chunking

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#142]
now we do the naive thing and store entire blobs as 1 file. we should add a blob-list abstraction (e.g. what camlistore/bup does) so we can use a rolling hash (like adler32 or rabin polynomials, whichever can be made faster in js) to invalidate only the blob chunks that change between versions of a blob

**Comment by karissa** [comment]
@mafintosh what's the status on this one?

**Comment by mafintosh** [comment]
@karissa we haven't begun to dive into this yet and it's not a beta feature but we should keep this one open as we definitely want to look into this later

**Comment by karissa** [comment]
k

**Comment by karissa** [comment]
@mafintosh will this happen with 1.0 with the fuse bindings?

**Comment by mafintosh** [comment]
@karissa yea i think so \o/

**Comment by jbenet** [comment]
we have an implementation of rabin chunking up over at https://github.com/whyrusleeping/chunker we got from a friend

**Comment by karissa** [comment]
A Rabin chunker is now being used in master
