### ISSUE TITLE
Need CLI and REST API for viewing history for a row

### ISSUE THREAD

**Issue by kayakr** [maxogden/dat#157]
I can't see in the docs how to list the history CLI or API? Given the analogy with git, would this be dat log {key} for example?

**Comment by karissa** [comment]
Thanks for trying out dat beta and submitting an issue. After a whole year of feedback from the community, we recently published a new version of dat... and it makes this issue obsolete. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
