### ISSUE TITLE
64-bit integers and other large numbers

### ISSUE THREAD

**Issue by rpedela** [maxogden/dat#158]
Given this tool is written in Node, I am curious how 64-bit integers and larger numbers are handled or planned to be handled?

**Comment by karissa** [comment]
@rpedela I recently built a [python library for dat](github.com/karissa/datpy) that can stream data in/out to numpy arrays or pandas. I don't really expect data scientists to use node.js for number crunching  anytime soon

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat. Would you mind trying out the new dat with npm install -g dat? You can read about the new dat announcement on the website and how it works in the docs.
