### ISSUE TITLE
common data structure for tabular data

### ISSUE THREAD

**Issue by dominictarr** [maxogden/dat#16]
Today I was looking for an npm module that could give me a linear regression,
of course, there where several,
but none of them agreed on the input format... array per column, or should it be array of rows?

To get good code reuse, it's necessary to have shared structures.
Like, streams, or callbacks. levelup and voxel.js all build on a shared base that is consistent.

I'm thinking, it's probably gotta be a stream of rows.

Where, probably, each row is an array... and maybe some way to look up headers?
then, we could have other modules that created subtables, or computed columns or aggregates.

While this isn't necessarily part of dat, it would be good to have something that works well with dat, since dat is already aiming to be modular.

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat which makes this issue obsolete (we are no longer focusing specifically on tabular use cases inside of this dat repository.) Would you mind trying out the new dat with `npm install -g dat`? In the meantime, I'm going to close this issue. You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
