### ISSUE TITLE
Secondary indices

### ISSUE THREAD

**Issue by astro** [maxogden/dat#163]
For a lot of use-cases secondary indices are great.

These secondary keys could originate from fields or by a mapping function (transformers applicable?), which could both be configured in the `dat.json`. There's also a third option of letting the user pass the key explicitly as `put()` metadata (Riak does this; I don't favour it for dat).

If this isn't supposed to be in core dat, an auxiliary component could consume the changes feed from a main repo and populate index repos with secondary keys. While having pointers to the primary keys as values saves space, an index with full values is faster to use. Repos that can be used independently justify fat values as well.

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat. Would you mind trying out the new dat with npm install -g dat? You can read about the new dat announcement on the website and how it works in the docs.

**Comment by astro** [comment]
The new release is kinda confusing. Can't find how to iterate over all keys.
