### ISSUE TITLE
disable versioning (to save space)

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#165]
storing versions should be an option that defaults to true. but if you say e.g. `version: false` then dat will operate in a mode where every only has the latest version of the data

**Comment by karissa** [comment]
+1 i like that idea, @jden

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat. Would you mind trying out the new dat with npm install -g dat? You can read about the new dat announcement on the website and how it works in the docs.
