### ISSUE TITLE
CLI command to observe changes

### ISSUE THREAD

**Issue by astro** [maxogden/dat#166]
To gain insight I would like to observe what changes. So far, I've tried: `dat cat --tail --live` but that spills out past changes.

**Comment by karissa** [comment]
Thanks for trying out dat beta and submitting an issue. After a whole year of feedback from the community, we recently published a new version of dat... and it makes this issue obsolete. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
