### ISSUE TITLE
Data not updating after put transformation

### ISSUE THREAD

**Issue by doowb** [maxogden/dat#170]
I'm having an issue getting the data to be added to the database with the actual transformed data.

The following code demonstrations the issue I'm having:

```js
'use strict';

var _ = require('lodash');
var dat = require('dat');
var through = require('through2');

var products = [
  'PROD-001',
  // 'PROD-002',
  'PROD-003',
  // 'PROD-004',
  // 'PROD-005',
  // 'PROD-006',
  'PROD-007',
  'PROD-008',
];

var transforms = [
  function () {
    return through.obj(function features (product, enc, next) {
      console.log('features', product);
      product.features = (product.features || []).concat([
        { color: 'red',   sizes: ['S', 'M', 'L', 'XL', 'XXL'] },
        { color: 'blue',  sizes: ['S', 'M', 'L', 'XL'] },
        { color: 'green', sizes: ['M', 'L'] }
      ]);
      product.transformed = (product.transformed || []).concat(['doowb-features']);
      // this.push(product);
      next(null, product);
    });
  },
  function () {
    return through.obj(function PROD1 (product, enc, next) {
      console.log('PROD1', product);
      if (product.id === 'PROD-001') {
        product.cost *= 0.80;
        product.transformed = (product.transformed || []).concat(['doowb-PROD1']);
      }
      // this.push(product);
      next(null, product);
    });
  },
  function () {
    return through.obj(function PROD8 (product, enc, next) {
      console.log('PROD8', product);
      if (product.id === 'PROD-008') {
        product.cost *= 0.50;
        product.transformed = (product.transformed || []).concat(['doowb-PROD8']);
      }
      // this.push(product);
      next(null, product);
    });
  }
];

var userDB = dat('./data/products/doowb', function (err) {
  if (err) {
    throw new Error(err);
  }

  var relatedDB = dat('./data/products/jon', { transformations: { put: transforms } }, function (err) {
    if (err) {
      throw new Error(err);
    }

    // get the products from userDB and pass them through the transforms
    var readOpts = {
      start: 'PROD-001',
      end: 'PROD-008'
    };

    var userStream = userDB.createReadStream(readOpts);
    userStream.pipe(through.obj(function (product, enc, callback) {
      var stream = this;
      if (!product || _.contains(products, product.id) === false) {
        this.push(product);
        return callback();
      }
      console.log('transforming product', product);

      relatedDB.put(product.id, product, {force: true}, function (err, updated) {
        if (err) {
          throw new Error(err);
        }
        console.log('Product ', updated.id, 'updated in related database');
        console.log(updated);
        stream.push(product);
        callback();
      });

    }));
  });

});
```
I have 2 different databases. The first `userDB` is using `createReadStream` to get a subset of rows, then put those rows into the second `relatedDB`.

When I add the `transformations` as options on `userDB` like `{transformations: { get: transformations}}` it works fine because the data is changed after the get, then passed into the `relatedDB` with `.put`.

When I run it with `transformations` as options on `relatedDB` like `{transformations: { put: transformations}}`, it runs through the transformations and I see the output of the modified data, but the `updated` record doesn't contain the changes.

I run `dat cat` from the command line to check and none of the data gets updated correctly.

From looking at the source code, it looks like transformations should be running, but I don't see it happening.

Thanks for any help.

**Comment by karissa** [comment]
Hey @doowb, we have re-written dat and have merged the new changes into master. Would you like to give dat another spin and see if you can find any bugs? Check out the 

[cli api](https://github.com/maxogden/dat/blob/master/docs/cli-docs.md)
[whitepaper overview draft](https://github.com/maxogden/dat/blob/master/docs/whitepaper.md)
and the [javascript api](https://github.com/maxogden/dat-core)

*high-five* I'll be watching dat issues and available in #dat on freenode if you want to talk to a human
