### ISSUE TITLE
Heroku implementation fails on file upload

### ISSUE THREAD

**Issue by waldoj** [maxogden/dat#173]
I just launched a new instance of Dat in Heroku, to try it out. It launched fine, and opening the web-based interface worked. But importing data does not work. When I paste in JSON, it fails with this error:

![json](https://cloud.githubusercontent.com/assets/656758/4085555/0533c01e-2f1f-11e4-8426-739317bc1ffd.jpg)

That appears after I paste in any JSON, including the inline example of `{"key": "pizza", "tasty": true}`.

When I try uploading a file, such as a CSV file, I receive this error:

![csv](https://cloud.githubusercontent.com/assets/656758/4085562/2677aa74-2f1f-11e4-935e-5d9149e43b6b.jpg)

This is with a brand-new Heroku account, using [heroku-dat-template](https://github.com/bmpvieira/heroku-dat-template#heroku-dat-template).

**Comment by karissa** [comment]
I think we can close this and open another issue to update heroku-dat-template for dat-beta.
