### ISSUE TITLE
Question: what happens if a record has a `key` and `version` value

### ISSUE THREAD

**Issue by taterbase** [maxogden/dat#175]
It seems they just get overwritten for now. Is it just accepted that you should transform these key names upon insertion?

**Comment by karissa** [comment]
@maxogden @mafintosh if the user decides to let `dat` auto-generate the key, but they have `key` in their dataset, there will be collision.

Do we want to make dat's autogenerated keys populate a property like `_dat_key`, or something terribly unique and unnecessary to look at most of the time?

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat. Would you mind trying out the new dat with npm install -g dat? You can read about the new dat announcement on the website and how it works in the docs.
