### ISSUE TITLE
CLI commands for CRUD

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#178]
This should be implemented like `dat blobs put` and `dat blobs get` are implemented but should have commands for:

```
dat rows get foo # returns 1 line of stringified JSON
dat rows put '{"hello": "world"}'
dat rows put single-json-object.json
dat rows delete foo
```

I'm not sure 100% sure on all of these APIs. I would probably start by implementing `get` and `delete` and then seek feedback of others first before doing put

**Comment by karissa** [comment]
@webmaven we went into deep cleaning, rewrote dat, and took out the http server from this repository, so now dat is transport agnostic. Check out [maxogden/dat-server](http://github.com/maxogden/dat-server) if you want to contribute to the http server. Woo!
