### ISSUE TITLE
question: similarity/difference vs. generationalsets?

### ISSUE THREAD

**Issue by ajschumacher** [maxogden/dat#184]
See: https://bitbucket.org/zc/generationalset

From their site:

> Generational sets (GSets) are designed to facilitate data synchronization between a server and clients.
> 
> Goals:
>
> * Make synchronization simple by sending all updates for a tree of sets at once.
> * Allow clients to be updated very quickly.
> * Reduce data-transfer volume by sending only changes.
> * Avoid conflict resolution.

**Comment by karissa** [comment]
Hey @ajschumacher 

Thanks for the pointer. I don't see that repo anymore, looks like it was taken down?

We are focused on the peer-to-peer scenario, with a focus on scientific use cases. If you want to find out more, check out the [whitepaper draft](https://github.com/maxogden/dat/blob/master/docs/whitepaper.md) about dat and check out the [cli documentation](https://github.com/maxogden/dat/blob/master/docs/cli-docs.md)

**Comment by ajschumacher** [comment]
Thanks @karissa! The repo was moved from bb to gh; I followed the link appearing on the bb page to here: https://github.com/zc/generationalset

Thanks for the link to the whitepaper draft! :eyes:
