### ISSUE TITLE
Wiki page for existing dat importer modules

### ISSUE THREAD

**Issue by akoenig** [maxogden/dat#193]
Just want to discuss if it makes sense to create a community-curated wiki page for existing dat importer modules (like [dat-npm](https://github.com/mafintosh/dat-npm) or [dat-geomagnetic](https://github.com/maxogden/dat-geomagnetic)). I mean, I'm looking forward for the upcoming central registry, but for the moment such a page could encourage people to write own importers. On the other side the core team can benefit and therefore learn from the respective use-cases.

What do you think? :)

/André

**Comment by karissa** [comment]
This exists! https://github.com/datproject/discussions/issues/5
