### ISSUE TITLE
ship the dat beta

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#195]
we're shooting for a dat beta release in april 2015. note that this doesn't include all the stuff in the [overall project roadmap](https://github.com/datproject/discussions/issues/9)

[here's a link to the list of issues for the beta milestone](https://github.com/maxogden/dat/issues?q=is%3Aopen+is%3Aissue+milestone%3Abeta)

These are the repos where most of the work will be happening: 

- https://github.com/maxogden/dat-core (core implementation/JS interface)
- https://github.com/maxogden/dat/tree/beta (command line interface)
- https://github.com/maxogden/dat-server (http server interface)

We are seeking feedback on our Beta APIs:

CLI: https://github.com/maxogden/dat/blob/beta/beta-cli-api.md
JS: https://github.com/maxogden/dat/blob/beta/beta-js-api.md

use this thread to discuss anything that doesnt fit in one of the issues above

**Comment by maxogden** [comment]
just an update, major work is underway now in both http://github.com/maxogden/dat-core and https://github.com/maxogden/dat/tree/beta. we hope to release in the new couple of weeks

**Comment by sckott** [comment]
:rocket:

**Comment by webmaven** [comment]
:shipit:

**Comment by joshmarinacci** [comment]
any updates?

**Comment by maxogden** [comment]
beta branch has been merged into master branch. still some work to do before a release, but for now you can `npm install dat@7.0.0-pre` to test out
