### ISSUE TITLE
LevelDB vs. ForestDB?

### ISSUE THREAD

**Issue by webmaven** [maxogden/dat#198]
Just came across this:
* https://github.com/couchbaselabs/forestdb
* https://github.com/couchbaselabs/forestdb/wiki/ForestDB-1.0-Beta
* http://blog.couchbase.com/next-generation-storage-engine-couchbase-server-and-couchbase-lite-forestdb-now-available-beta

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat... and it makes this issue obsolete. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
