### ISSUE TITLE
Data provenance

### ISSUE THREAD

**Issue by todrobbins** [maxogden/dat#20]
What kinds of considerations are being made for the provenance of data? For instance, multiple groups are working on this issue (see below). I'm a lurker on the repo but very interested in its future.

_Provenance resources:_
* http://infolab.stanford.edu/panda/
* http://openprovenance.org/
* http://www.w3.org/standards/techs/provenance#w3c_all

**Comment by joehand** [comment]
There have been significant changes in Dat since previous version. The 1.0 should have much better support for data provenance!
