### ISSUE TITLE
dat for syncing and Academic Torrent for long-term storing

### ISSUE THREAD

**Issue by jibe-b** [maxogden/dat#202]
In terms of purpose, dat is clearly intended for datasets that are susceptible to be updated often. Academic Torrent (http://academictorrents.com) is build for long-term stable distributed storage.

How about a feature like publishing a dataset that will no longer change to Academic Torrents ?

Best regards,

Jibé

**Comment by karissa** [comment]
This should be totally doable now. After a whole year of feedback from the community, we recently published a new version of dat. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
