### ISSUE TITLE
dat listen -d

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#206]
would be cool to be able to run a dat server in the background as a daemonized process

so in addition to the current `dat listen` behavior which starts the server in the current process we would have a flag to run it daemonized, e.g. `dat listen -d` or `dat listen --background` or `dat listen --detach`

this would spawn a new forked process with dat running. it should probably have a log dir option and a PID option as well that default to something sensible

pros:

- can use one terminal to do stuff w/ multiple dats (simplifies usage for newbies)
- convenience

cons: 

- if dat crashes when running in the background it's more difficult to know and find out

**Comment by mafintosh** [comment]
since the new replication model spawns a remote process instead of relying on a server running this isn't needed anymore is it?

**Comment by karissa** [comment]
+!
