### ISSUE TITLE
Recommendations for including schema definitions?

### ISSUE THREAD

**Issue by joyrexus** [maxogden/dat#209]
Is there currently a preferred way to include schema definitions with a dat?

#### Notes

@maxogden has [stated his preference](https://github.com/maxogden/dat/issues/52#issuecomment-39909130) for keeping metadata and data in separate files (i.e., having a distinct file with metadata, rather than having a header with metadata included with the datafile).

@mafintosh has discussed a [`schema.json`](https://github.com/maxogden/dat/issues/85#issuecomment-42766376) file describing the global encoding/decoding format for each row of data in dat.

Note also the proposals for a dat schema api in [#171](https://github.com/maxogden/dat/issues/177) and [#191](https://github.com/maxogden/dat/issues/191). 

The need for dataset metadata conventions more generally should perhaps be understood in the context of dataset packaging and registry proposals:

See these comments on the `dat` freenode channel ...

* [including schema definitions bundled with a dat](https://botbot.me/freenode/dat/2014-10-10/?msg=23253771&page=1)
* [preferred way to include schema definitions with a dat?](https://botbot.me/freenode/dat/2014-10-14/?msg=23471004&page=1)

... and [this discussion](https://github.com/dataprotocols/dataprotocols/issues/110) on package file conventions for datasets.

@jbenet notes that he's working with @maxogden with [the aim of making dat/datadex interoperable](https://github.com/dataprotocols/dataprotocols/issues/110#issuecomment-39648377). See also @maxogden's comments at the very end of [this article](http://thenewstack.io/the-new-stack-makers-dats-max-ogden-building-a-github-for-data/).

See, finally, [this related proposal](https://github.com/datproject/discussions/issues/11) for a dat registry.

**Comment by joyrexus** [comment]
To my mind, using the [json table schema](http://dataprotocols.org/json-table-schema/#schema) as a basis for defining a schema within the `dat.json` file seems like the way to go.  The strawman example in #240 sort of hints at something like this.

I'm personally most interested in being able to **declaratively** specify [enum types](https://developers.google.com/protocol-buffers/docs/proto#enum) within a given dataset.  (Regrettably, enums are not easily specified via json-table-schema's set of [field constraints](http://dataprotocols.org/json-table-schema/#field-constraints).)

I've worked with sqlite as a tabular datastore for so long, I can't help but think of schemas as integral parts of any dataset (even single-table datasets) because they can convey much of the semantic content of your data.

**Comment by karissa** [comment]
Yeah, the json table schema seems to make sense. I also see the value in declaratively specifying enum types, but it's still not clear how that will be integrated with dat. 

It might make sense to first start with an experimental json table schema that is stored in a separate file, and the dat.json file can subsume or contain it at some point later if it makes sense in practice.

**Comment by karissa** [comment]
(the goal being here to keep components as separate as possible particularly while in heavy development)

**Comment by mitar** [comment]
What is relation between JSON schema and JSON table schema?

**Comment by karissa** [comment]
Looks like JSON schema is a little more flexible whereas json table schema is specifically created for column-wise datasets.

**Comment by joyrexus** [comment]
> What is relation between JSON schema and JSON table schema?

Check out the discussion on dataprotocols/dataprotocols#110, perhaps starting [here](https://github.com/dataprotocols/dataprotocols/issues/110#issuecomment-39664649).

**Comment by mitar** [comment]
Hm, I read that, but that is mostly a discussion about JSON-LD, not JSON schema? Or did I miss something? JSON schema and JSON-LD are trying to address a bit different needs, I think. JSON-LD explains what is the semantic meaning of values, while JSON schema tells if the data is in the expected format and what types are values. They can coexist as well.

But I am still unsure why not using an existing standard like JSON schema: http://json-schema.org/ Then you can use packages like: https://www.npmjs.com/package/jsck to check if each row corresponds to this schema, for example.

**Comment by joyrexus** [comment]
@mitar oi, right ... I conflated the two (json schema and LD).

The nice thing about the json table spec is that its a ready-made spec specifically for tabular data (which is what dat deals with), well-documented, with clear and simple examples.  You could of course do something quite similar with JSON Schema.

Is there any hope of the dat team advocating an existing spec (or simplified variant thereof) that could be included in the `dat.json` under, say, a `schema:` key?

**Comment by mitar** [comment]
Hm, I do not see how JSON schema is not suitable for tabular data? JSON schema defines schema for the row, and then each row has that schema?

I am just saying that JSON schema is a popular approach with many existing tools. It is an [IETF standard](https://tools.ietf.org/html/draft-zyp-json-schema-01). It is pretty similar to JSON table schema, except that it is already a standard. See [examples here](http://json-schema.org/examples.html). See [this tool as well](http://jsonschema.net/#/).

**Comment by mitar** [comment]
See all [available NPM packages for JSON schema](https://www.npmjs.com/search?q=json-schema).

**Comment by joyrexus** [comment]
@mitar Yes, of course. No objections to JSON schema.  My question is rather whether there are going to be any established conventions for including schema info with a dat.

**Comment by karissa** [comment]
@joyrexus I think having established conventions is the way to go

**Comment by karissa** [comment]
Thanks for trying out dat beta and submitting an issue. After a whole year of feedback from the community, we recently published a new version of dat... and it makes this issue obsolete. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
