### ISSUE TITLE
Support for more datatypes

### ISSUE THREAD

**Issue by shoshanaly** [maxogden/dat#234]
From the docs: "data can be either tabular (rows & cells) or blobs"

What about other data types? The research areas I'm most familiar with (natural language processing, cognitive science) model much of their data using trees. It is possible to use blobs for this, of course, but native handling of trees (or graphs, etc.) would be great. I imagine other research fields have their own modeling needs as well.

**Comment by karissa** [comment]
it might be nice to see this as another "store type".. maybe we should be thinking about this as part of our beta efforts in making blobs first-class citizens.

**Comment by karissa** [comment]
We are focusing on arbitrary Buffers now in 1.0, so people could build apps on top of dat for their particular use case outside of this repo.
