### ISSUE TITLE
Create browser version

### ISSUE THREAD

**Issue by Ti-webdev** [maxogden/dat#235]
Add support web client with websocket replication dat

**Comment by karissa** [comment]
:)

**Comment by timkuijsten** [comment]
is there a browser version planned, maybe using IndexedDB?

**Comment by karissa** [comment]
I am working on a browser example over at http://github.com/Karissa/dat-browserify

You can also see a working browser demo of just the storage component over at mafintosh/hyperdrive on the gh-pages branch

**Comment by timkuijsten** [comment]
Cool, I'm working on a browser based solution as well that syncs with my leveldb server: https://github.com/Netsend/persdb/tree/master/browser
