### ISSUE TITLE
expand tildes in cli paths

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#239]
we currently interpret `--foo=bar` as `{foo: bar}` and `--foo bar` as `{foo: true, _: ['bar']}`

we should probably document this options behavior more clearly in the CLI usage/help

however, the only thing that doesnt work as expected is paths with `~` in them. 

![screen shot 2014-12-07 at 12 04 27 pm](https://cloud.githubusercontent.com/assets/39759/5332374/412e346c-7e09-11e4-8d9d-ae44fcabf92a.png)

i propose we fix it by using this to expand them manually since bash doesn't handle it for us
https://www.npmjs.org/package/expand-home-dir

**Comment by karissa** [comment]
This is fixed now.
