### ISSUE TITLE
data sources/schema mapping support in dat.json

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#240]
we want a way to use `remotes` in `dat.json` to hold configuration data not just for other dats (which is how it is used now) but also to describe readable and writable tabular data stores. 

here's a strawman proposal for discussion:

```json
{
  "name": "npm",
  "remotes": {
    "couch-npm": {
      "readable": true,
      "module": "couchdb-dat-sync",
      "url": "http://max.iriscouch.com/npm",
      "schema": {
        "name": {"rename": "key", "type" :"string"},
        "readme": "string",
        "versions": "string"
      }
    }, 
    "sqlite-search": {
      "version": false,
      "writable": true,
      "module": "sqlite-dat-fulltext",
      "schema": {
        "name": "VARCHAR",
        "readme": "TEXT"
      }
    }
  }
}
```

the use case here is a dataset like the http://npm.dathub.org/ which is a dat. imagine you want to specify a remote like `couch-npm` which is the couchdb that the npm data is originally stored in. this remote should have enough information for a theoretical module `couchdb-dat-sync` to connect to and parse the remote data into a protocol buffers schema. in the `schema` key you can specify types from this table https://developers.google.com/protocol-buffers/docs/proto#scalar

for these sync modules you could either give dat JSON data or protobufs. if you give dat protobufs you have to also give dat your protobuf schema at init time.

the `sqlite-search` entry is an example of a writable remote, meaning it specifies how to take the protobuf schema stored in dat and turn it into a target data format, in this case sqlite data types. the `sqlite-dat-fulltext` module would get the `schema` config and would have to implement protobuf -> sqlite data mappings.

**Comment by karissa** [comment]
Could this be somewhat like a nested dat? If dat can handle dependencies, that'd be awesome. (i.e., #298)
