### ISSUE TITLE
make clone size estimate more accurate

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#241]
![screen shot 2014-12-09 at 1 57 02 pm](https://cloud.githubusercontent.com/assets/39759/5366750/49cba610-7fab-11e4-9380-71f1463a2e57.png)

I think this number is wrong because it's the size after the clone HTTP request gets ungzipped but before the data gets re-compressed with snappy compression in leveldb. On disk the size of npm --skim after clone is only 750mb. Honestly though this number should just the amount of data transferred over the network, pre-gunzip

**Comment by karissa** [comment]
Closing with 1.0
