### ISSUE TITLE
decentralized data model

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#254]
So far dat has been centralized, e.g. like SVN, theres a central server with the global state and clients have coordinate with the state of the server. As part of [the beta](https://github.com/maxogden/dat/issues?q=is%3Aopen+is%3Aissue+milestone%3Abeta) release coming up we want to change the way we fundamentally store data so that it can support high level operations like merging and branches. 

@mafintosh has been researching this for a few months and has landed on an API that we like: https://github.com/mafintosh/hyperlog

This issue is to discuss hyperlog + dat integration for the beta milestone

**Comment by maxogden** [comment]
this is now implemented in the `beta` branch

**Comment by ekg** [comment]
Congrats, this is a *big* deal!
