### ISSUE TITLE
make blobs a first class feature

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#255]
currently blobs are attached to rows, but this makes the dat API for blobs cumbersome and annoying to use. it would be better if rather than having a one-to-many relationship between rows and blobs we just made everything a row, and a row either tabular or a blob

**Comment by karissa** [comment]
We talked about an api today. 

We decided that:
  1. Files are the new first-class blob feature. formerly known as blobs
  2. Datasets were high-level entities, with metadata. (implemented with sublevels)

There was one definite proposal:
### Datasets contain files and rows
```bash
## create a dataset
dat datasets create <dataset-name> 
## add a file to a dataset
dat files add <dataset-name> <filename-or-stream>
## add rows to a dataset
dat rows add <dataset-name> <filename-or-stream>
 ## lists datasets
dat datasets
## cat rows
dat rows <dataset-name>
## cat files
dat files <dataset-name>
```

**Comment by karissa** [comment]
Updating the version of data:

```bash
$ dat files add cities my_us_cities_viz.png
This will override my_us_cities_viz.png at c2342d (y/n): y
...done
maxogden updated my_us_cities_viz.png to be253f on Sat Jan 17, 9:33pm
```

adding/overwriting rows
```bash
$ echo '{"population": 609457, "key": "Portland, OR, USA"}'  | dat cities rows add
This will update 1 row at c2342d (y/n): y
...done
maxogden updated "Portland, OR, USA" to be253f on Sat Jan 17, 9:33pm
```

for command line
```bash
$ dat files add cities my_us_cities_viz.png --no-prompt/--force(?)
maxogden updated my_us_cities_viz.png to be253f on Sat Jan 17, 9:33pm
```
