### ISSUE TITLE
How can I configure dat to use PostgreSQL as the backend

### ISSUE THREAD

**Issue by aziz** [maxogden/dat#274]
I've added `"leveldown": "sqldown",` to my `dat.json` and installed `sqldown`, `pg` and `pg-query-stream` 
using `npm install --save pg pg-query-stream sqldown`

How can I configure sqldown to use a postgres connection. Right now when I run `dat serve` it tries to connect to a sqlite3 database that obviously does not exists.

**Comment by karissa** [comment]
Hey, sorry for the late reply. This month has been a bit busy getting the beta ready. 

This feature is still experimental but we have a working version that deploys to heroku. You can see [here](
https://github.com/bmpvieira/heroku-dat-template/blob/postgres/dat.json) where in the dat.json file, there is a place to put your ```DATABASE_URL``` connection string:

```json
{
  "leveldown": {
    "path": {
      "env": "DATABASE_URL"
    },
    "module": "sqldown"
  }
}
```

I'll go ahead and document this
