### ISSUE TITLE
github->dat porting tool/module

### ISSUE THREAD

**Issue by karissa** [maxogden/dat#275]
it'd be nice to be able to provide github as a storage solution/backend module for dat. it might also be nice to have an github -> dat importer or something.

**edit: this might not even need a technical solution -- it could be solved by writing a good "github importer guide"**

One example where this could be immediately useful is in cases like the following link, where a political scientist has uploaded many csv files which are *just* too big for Github to display, but small enough where github still seems like a viable option for version control. (github shows "We can't beautify this..) 

https://github.com/ulfelder/democracy-measurement-model/blob/master/data.out

Another example is where one wants to port data from a github repo directly into a dat instance. so they *were* using github for version control, but now want a more robust solution and are looking for dat as an alternative.

**Comment by karissa** [comment]
this might not even need a technical solution -- it could be solved by writing a good "github importer guide"

**Comment by thadguidry** [comment]
Another issue that might come up is trying to store a large file in Github regardless of displaying or not in the Github's web view.

Github's Large File support and Disk Quota are properly documented here: https://help.github.com/articles/what-is-my-disk-quota/

**Comment by joehand** [comment]
This issue was moved to datproject/discussions#51
