### ISSUE TITLE
"all or nothing" boolean for pulls

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#277]
if you pull, and it crashes halfway through, what happens? the default behavior for now will be a 'rolling pull' that can just begin where it left off, but you should be able to also say 'allOrNothing: true' to a pull to make it write to a e.g. https://github.com/mafintosh/level-temp instance until the pull finishes, then move the data into the real datastore after network is done.

this would be 2-3X more write/reads but it would be "safer"

**Comment by karissa** [comment]
@maxogden @mafintosh what's the current status on this/what happens at the graph level? I'd like to create some sort of user documentation around this.

**Comment by mafintosh** [comment]
a pull always leaves the graph in a consistent state and we currently only support rolling pulls. if you really want to make sure you got a specific revision after a pull crashed you can always try to do a `dat checkout <some-hash>` which will fail if it didn't fetch `<some-hash>` before crashing

**Comment by karissa** [comment]
what do you mean by 'a rolling pull'?

**Comment by mafintosh** [comment]
what @maxogden describes as a 'rolling pull' above. if a pull fails and you pull again it won't have to refetch everything - it'll just continue from where it failed

**Comment by karissa** [comment]
Ohh ok ;)

**Comment by karissa** [comment]
Solved in 1.0 with hyperdrive
