### ISSUE TITLE
js-api.md documents non-existing methods

### ISSUE THREAD

**Issue by chuesler** [maxogden/dat#283]
In dat/docs/js-api.md, several methods are documented which don't actually exist.

* cat
* dump
* config

I'm not sure how much of an issue that is, but thought I'd mention it ;)

**Comment by karissa** [comment]
@chuesler thanks for the heads up, sorry for the late reply, your issue got a bit burried. check out the beta branch right now for current development.

**Comment by karissa** [comment]
hey @chuesler we just merged the dat beta. Check out the new JS api at http://github.com/maxogden/dat-core
