### ISSUE TITLE
simple merge operation

### ISSUE THREAD

**Issue by karissa** [maxogden/dat#292]
https://github.com/karissa/dat-visualdiff

**Comment by karissa** [comment]
dat-visualdiff: dat->html
visualdiff (cmdline tool): csv x2->dat->html->browser
dat: dat->html->browser/atom-shell

**Comment by maxogden** [comment]
im doing `dat merge --left`, `--right` and `--random` now so we can at least have those built in for easy cli merging

**Comment by karissa** [comment]
+1
