### ISSUE TITLE
nested dats

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#298]
opening for feedback/discussion

we are talking about the dat folder structure. Here are two proposals (A on the left, B on the right)

![screen shot 2015-04-09 at 10 20 50 am](https://cloud.githubusercontent.com/assets/39759/7072549/38228310-dea2-11e4-9368-6b59c0b38043.png)

I'm inclined to go with B, as having everything in a folder like `datasets` (along the lines of `bower` or `node_modules`) seems unnecessarily namespaced. The `dat clone` can just bail or append `-1` to folder names if you try and clone into something with a clashing folder name.

With B, from the root, you could do e.g. `dat cat sweden population`, or `cd sweden/population && dat cat` and it would be the same

Another cool thing about this is we could implement dataset dependencies in the future.... but that's a separate discussion

Inside each dat repo there will be a `dat.json` for config (name, description etc) and a `.dat` folder where the graph lives. Inside each named dataset folder it could either be another nested dat repo or a dataset, in the latter case it would just be a separate leveldb for that specific dataset (see the beta [datasets](https://github.com/maxogden/dat/blob/beta/beta-cli-api.md#dat-datasets) for more info)

**Comment by karissa** [comment]
I think it should be B but we discussed that it'd probably have just a dat.json in the root (sweden and denmark, in this example)

See this for a UX proposal that mentions this behavior at the end https://github.com/maxogden/dat/issues/295

**Comment by karissa** [comment]
This would be nice for hdf5-like interface support (since hdf5 also supports nesting)
