### ISSUE TITLE
dat concurrency model

### ISSUE THREAD

**Issue by nylen** [maxogden/dat#299]
What is dat's concurrency model?

Is it safe to write to a dat before another write finishes from the same process?  What about from another process?

If one process is writing, will `put` transformations in another process be called?

**Comment by nylen** [comment]
I'm having some issues that could be prevented by a better understanding of what's going on here.  It looks like it is pretty easy to break `dat` by attempting to access the same database from multiple processes (I did this by accident a few times).

The symptoms I'm seeing are that I try to create a `dat` instance in JS, but my callback function is never called and the process exits.  If there's an error, something is preventing it from being shown. Removing the `.dat/store.dat/LOCK` file seems to clear it up, but this makes me a little nervous.

`dat` could certainly behave more robustly here (fail loudly and provide a clear indication of how to fix the problem, whether in the error message or docs).

**Comment by maxogden** [comment]
Sorry for not replying, we're trying to ship the beta version. One of the things we've fixed in beta is this issue, partially with https://github.com/mafintosh/multileveldown

**Comment by nylen** [comment]
Good to see that y'all are still actively maintaining dat.  It has some rough points but I love the concept and see lots of potential uses for it.

**Comment by karissa** [comment]
I think this is dealt with now!
