### ISSUE TITLE
Where are the streaming interfaces?

### ISSUE THREAD

**Issue by nylen** [maxogden/dat#300]
> Dat is an open source project that provides a streaming interface between every file format and data storage backend.

To me, this means:

1. you have *import* adapters for different data sources
2. you have *export* adapters for different data destinations

For point 1, OK, dat accepts data lots of different ways.

For point 2, I'd like to be able to say `dat.on('put', ...)` to automatically export certain rows.  I got something working using a `put` transformation but it seems like that's not really what that feature is for.

My immediate use case is to sync events for an organization among multiple sites (let's say Meetup, Google+, and Facebook).  I see how to pull from one site and push to others using the above model.  I think fleshing out this approach would be very powerful for a large variety of data problems.

Maybe you also need a third piece: *filters* that know how to transform between different data types?

**Comment by thadguidry** [comment]
@nylen it sounds like Zapier might be more of what your looking for in my opinion.

**Comment by nylen** [comment]
Yes, that would probably work for my current use case, but I'm ultimately more interested in an open source solution that can handle this kind of task.

**Comment by jzjzjzj** [comment]
> Maybe you also need a third piece: filters that know how to transform between different data types?

[jbenet/transformer](https://github.com/jbenet/transformer)

> [![dat](http://img.shields.io/badge/Development%20sponsored%20by-dat-green.svg?style=flat)](http://dat-data.com)
> [..]
> Transformer is part of Dat Project.

It looks kind of dead, though.

**Comment by nylen** [comment]
> [jbenet/transformer](https://github.com/jbenet/transformer)

This looks really nice, thanks!

**Comment by nylen** [comment]
Seems related to #296: to have a stream you have to have two ends, and right now only the *import* end of `dat` is implemented.

**Comment by balupton** [comment]
I'm also wondering the exact same thing... https://github.com/maxogden/dat/issues/305#issuecomment-109732740

**Comment by mafintosh** [comment]
@balupton we are adding `dat export` which is an output stream of data. it is implemented in the master branch if you want to play around with it :)

**Comment by karissa** [comment]
I think we can close this
