### ISSUE TITLE
versioning with entire data not only with each rows changed

### ISSUE THREAD

**Issue by thechunsik** [maxogden/dat#306]
the version mechanism is for each rows changed. but like git, it would be better to manage versions with entire data not only the rows. is it working already ?

**Comment by ekg** [comment]
I believe this is provided by checkpoints in the log of row-level changes
to the database.

**Comment by karissa** [comment]
the version mechanism is by row, but also by table. the by-table versioning is the most important.

**Comment by jeroenooms** [comment]
@karissa I'm not sure I understand what checkout does. A `dat checkout` does not change the head, and also the output from `dat cat` seems to be exactly the same after checking out an old commit. What is the best way to `dat cat` the dataset as it was in version x?

```bash
dat heads
95b776c2f10bc2ed7fe7d36ef7a22c8a1694cde4ecec5d1be65a8306fb552c8b

dat checkout 065bff55728d6cf91dbe0a109ce8bab95402b0193d56ca5bcac042f4638e36a7
Checked out to 065bff55728d6cf91dbe0a109ce8bab95402b0193d56ca5bcac042f4638e36a7

dat heads
95b776c2f10bc2ed7fe7d36ef7a22c8a1694cde4ecec5d1be65a8306fb552c8b
```

**Comment by karissa** [comment]
@jeroenooms Checkout was broken, which is now being handled by #324. Now, mafintosh/dat-core handles versions by import batch (i.e., an entire data version: table or file) instead of by row. Thanks @thechunsik !
