### ISSUE TITLE
save the key for the dataset

### ISSUE THREAD

**Issue by karissa** [maxogden/dat#311]
```
dat add flights.csv --key=pk --dataset=flights
```

in subsequent adds, `--key=pk` is implicit 

```
dat add flights2.csv --dataset=flights
```

but you could still do
```
dat add flights3.csv --dataset=flights --key=mykey
```

on all other datasets, the key is still being autogenerated
```
dat add flights4.csv --dataset=some-other-dataset
```

**Comment by mafintosh** [comment]
:+1: an api for getting/setting the current key props would be useful for this as well

**Comment by karissa** [comment]
@mafintosh where do you think we should save it? somewhere in dat-core?

**Comment by karissa** [comment]
@mafintosh or a config file?
