### ISSUE TITLE
Get new keys for added data

### ISSUE THREAD

**Issue by jeroenooms** [maxogden/dat#312]
It would be useful if `dat add` had an option to return an array of (auto-generated) keys for the successful inserts, like a receipt. Thereby the client knows which key to use to update this row in future. Currently it is difficult to implement syncing because the client doesn't know where the data went.

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
