### ISSUE TITLE
no `index.js` in the beta branch

### ISSUE THREAD

**Issue by myf** [maxogden/dat#314]
.. while the `package.json` is calling for index.js for `main`, should it be changed to `cli.js` or just get rid of that line?

**Comment by karissa** [comment]
@myf thanks for the reminder! I just made index.js an alias to (maxogden/dat-core)[maxogden/dat-core), because then people can get to the js api by just doing require('dat')

**Comment by maxogden** [comment]
we should get rid of it :)

**Comment by karissa** [comment]
yeah i never merged that branch we can close this issue
