### ISSUE TITLE
dat status with two heads

### ISSUE THREAD

**Issue by karissa** [maxogden/dat#316]
what should the output be for `dat status` when there are multiple heads ?

**Comment by mafintosh** [comment]
the head of your current branch (`db.head`)

**Comment by karissa** [comment]
db.head returns null it seems

**Comment by mafintosh** [comment]
the db has to be open for it to be populated (and the dat non empty). the db is lazily opened so the head should be there after any async operation. optionally you can call .open to "force" it open

```
var db = dat(...)

db.open(function () {
  console.log(db.head) // returns hash
})

db.put(..., ..., function () {
  console.log(db.head) // returns hash
})
```

**Comment by karissa** [comment]
I seeeee.. i didn't expect properties to change when `db.open` is called.

**Comment by mafintosh** [comment]
This is the only one that changes since its the only non function property.
