### ISSUE TITLE
dat core features

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#317]
here are issues we need in dat-core for the beta dat cli:

- [x] https://github.com/maxogden/dat-core/issues/17
- [x] https://github.com/maxogden/dat-core/issues/18
- [x] https://github.com/maxogden/dat-core/issues/10
- [x] https://github.com/maxogden/dat-core/issues/6
- [x] https://github.com/maxogden/dat-core/issues/9
- [x] https://github.com/maxogden/dat-core/issues/11
- [x] https://github.com/maxogden/dat-core/issues/24

**Comment by maxogden** [comment]
When I import a csv I get this state:

```
🐈  dat-beta status
Current version is bb08a5c9179f20abb40be1ce4ac317a3d055dd6610dc8913b895246af90dc1fa (latest)
1 dataset, 8416 keys, 0 files, 8416 versions, 2.95 MB total
Last updated yesterday (Tue Jun 02 2015 13:46:54 GMT-0700 (PDT))
```

Only thing missing is that it should be 1 version instead of 8416 versions IMO. So we need to make sure that the three mutate operations (write stream, put, del) get represented as 1 version in the graph by default. @mafintosh do you think #17 in the list above will fix it?

**Comment by mafintosh** [comment]
@maxogden yup - transactions are the way to go to fix this

**Comment by mafintosh** [comment]
there is a PR for transactions here, https://github.com/maxogden/dat-core/pull/19 but I'm not completely sure about the API which is why it isn't merged yet.

**Comment by karissa** [comment]
can we close this?
