### ISSUE TITLE
Broken Link on Homepage

### ISSUE THREAD

**Issue by Miserlou** [maxogden/dat#329]
Tiny bug, but at http://dat-data.com/, "Read more here" links to https://github.com/maxogden/dat/blob/master/docs/dat-stable-alpha.md - which is a 404. Easy fix!

Thanks for this awesome project.

**Comment by karissa** [comment]
hey @Miserlou sorry about that, we are in the process of upgrading everything to beta!

The new docs are here:  https://github.com/maxogden/dat/blob/master/docs/cli-docs.

And an intro to/overview of dat: https://github.com/maxogden/dat/blob/master/docs/whitepaper.md
