### ISSUE TITLE
dat fork

### ISSUE THREAD

**Issue by karissa** [maxogden/dat#332]
for forking manually

Scenario: Im on the latest checkout, ab23d12. I want to experiment on this dataset, which will be a pretty destructive transformation.

Currently,

```
dat import updates.csv 
```

will not create a fork on the current branch, but add d as the new latest.

```
a
|
b
|
c
|
d (latest)
```

When other people `dat pull`, they'll see 'd' as the latest checkout if they haven't changed their local repo. 

What I'd really like is a fork, so that when they pull, they don't have to use my experimental version.

```
$ dat fork
Current version is bsbd234
$ dat forks 
ab23d12
bsbd234
$ dat import updates.csv
```

So it'd look like:

```
a
|
b
| \
c  d <- (c is still 'latest')
```

**Comment by mafintosh** [comment]
@karissa you can do this currently using a checkout

```
dat checkout b
dat import updates.csv
```

**Comment by karissa** [comment]
@mafintosh I really want `d` to be a copy of `c`, though, so they'd have to do

```
dat checkout b
dat export -d dataset --checkout=<c> | dat import -d dataset
dat import updates.csv
```

**Comment by mafintosh** [comment]
@karissa ok i think i understand the use-case. we could easily add this by just copying the c graph node internally and giving it a bit of new metadata so it gets a new hash.

**Comment by karissa** [comment]
+1

**Comment by finnp** [comment]
Wouldn't it be better to use something like git branches? So instead of copying a graph node, there would be a list of tags that you could assign to certain nodes.

So it would be more like:
```
dat branch experiment
dat checkout experiment
dat import updates.csv
```


After `dat branch`:
```
a
|
b
| 
c <- latest, experiment
```

After the import
```
a
|
b
| 
c <- latest
|
d <- experiment
```
