### ISSUE TITLE
BUG : dat: clone is not a valid command with 7.0.0-pre

### ISSUE THREAD

**Issue by clemsos** [maxogden/dat#337]
Hey,

I just did a ```npm install -g dat``` then I tried to dat clone and I get this error. 
The version is 7.0.0-pre . Everything works fine when I update to 6.9.7 
(This is my first time using dat) 

```
clemsos@clemsos:~/Dev/dat$ dat -v
7.0.0-pre

clemsos@clemsos:~/Dev/dat$ dat clone http://eukaryota.dathub.org eukaryota
dat: clone is not a valid command
```

**Comment by maxogden** [comment]
@clemsos hi, sorry things are a bit in flux right now -- we're trying to update everything for the upcoming beta. If you wanna give the newer dat a spin then try `npm install dat -g` again (hopefully you get `7.0.0-pre-2` now), or if you wanna play with the old dat you can do `npm install dat@6.9.6`

**Comment by clemsos** [comment]
@maxogden no worries, I understood it may be the case and was just notifying. Actually, dat is great and looks very useful. What is the best way to start contributing ? Thansk !
