### ISSUE TITLE
sha1... why not Blake2 ?

### ISSUE THREAD

**Issue by paulharris** [maxogden/dat#344]
AFAIK Blake2 would be a better choice for a hash if starting from scratch.
Didn't I read something about that related to git's design choices?

**Comment by maxogden** [comment]
on my phone so apologies for the short reply, but we are using sha256 and
not sha1. we are interested in jbenet/multihash but there are some
implementation issues to overcome there

On Wednesday, June 17, 2015, paulharris <notifications@github.com> wrote:

> AFAIK Blake2 would be a better choice for a hash if starting from scratch.
> Didn't I read something about that related to git's design choices?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxogden/dat/issues/344>.
>


-- 
Sent from my phone

**Comment by paulharris** [comment]
ah, i saw "sha1" mentioned somewhere in the docs or was it from the command line.
sha256 much better :)
multihash looks cool
