### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by paulharris** [maxogden/dat#345]
$ dat merge acfc
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: You checkout hash must be at least 16 characters

**Comment by maxogden** [comment]
Thanks for the report, I think we aren't forwarding an error something from `dat-core`... @mafintosh can you spot where this is coming from?

**Comment by mafintosh** [comment]
this is fixed in latest dat-core so when dat switches to dat-core `^3.0.0` this should be fixed here as well
