### ISSUE TITLE
If we wanted to publish a refined version of an important but poorly maintained government database and set the standard for "doing it right" with dat, how would we do it?

### ISSUE THREAD

**Issue by palewire** [maxogden/dat#347]
Asking for a "friend."

**Comment by maxw3st** [comment]
GitHub

On Tue, Jun 23, 2015 at 9:03 PM, Ben Welsh <notifications@github.com> wrote:

> Asking for a "friend."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxogden/dat/issues/347>.
>



-- 
Max West

**Comment by palewire** [comment]
Thanks. Could you point to an example that you think is done particularly
well?
