### ISSUE TITLE
dat equivalent of git reflog?

### ISSUE THREAD

**Issue by ZECTBynmo** [maxogden/dat#352]
Is there any way to get a list of all SHAs attached to a stream? I've been looking around, and haven't found anything yet. Will I have to store my SHAs externally and keep track of them myself?

Looking for some equivalent of git reflog

Thanks for all the amazing work dat team!

**Comment by karissa** [comment]
There's `dat log`, but right now we don't have anything any more sophisticated than that. 

If you do 'dat checkout latest' you'll get to the latest one, which from there you can do a `dat log` to get all changes in the stream.

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat... and it makes this issue obsolete. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).

**Comment by karissa** [comment]
This issue might be quite related to https://github.com/mafintosh/hyperdrive/issues/18
