### ISSUE TITLE
"dat clone http://npm.dathub.org --skim" no longer works -- "Error: Invalid remote"

### ISSUE THREAD

**Issue by govpack** [maxogden/dat#353]
hi, 

where are the scripts to import a fresh instance of the npm metadata from couchDB? I thought the synchronization features of dat would be keeping things up to date, but this endpoint is no longer working:

```
dat clone http://npm.dathub.org --skim
```
i don't mind repeating the importation phase -- if someone could point out the code which made the previously working npm dat in the first place, thanks

Elapsed      : 0 s
Pulled       : 0 B       (0 B/s)

[1A[2K[1A[2K[1A[2KElapsed      : 0 s
Pulled       : 0 B       (0 B/s)

[1A[2K[1A[2K[1A[2KElapsed      : 0 s
Pulled       : 0 B       (0 B/s)

[1A[2K[1A[2K[1A[2KElapsed      : 0 s
Pulled       : 0 B       (0 B/s)

[1A[2K[1A[2K[1A[2KElapsed      : 0 s
Pulled       : 0 B       (0 B/s)

[1A[2K[1A[2K[1A[2KElapsed      : 0 s
Pulled       : 0 B       (0 B/s)

[1A[2K[1A[2K[1A[2KElapsed      : 0 s
Pulled       : 0 B       (0 B/s)

[1A[2K[1A[2K[1A[2KElapsed      : 0 s
Pulled       : 0 B       (0 B/s)

[1A[2K[1A[2K[1A[2KElapsed      : 0 s
Pulled       : 0 B       (0 B/s)

[1A[2K[1A[2K[1A[2KElapsed      : 0 s
Pulled       : 0 B       (0 B/s)

[1A[2K[1A[2K[1A[2KElapsed      : 1 s
Pulled       : 0 B       (0 B/s)

Error: Invalid remote

**Comment by karissa** [comment]
Sorry, the example isn't up and running right now

**Comment by karissa** [comment]
@govpack hey, we just put npm.dathub.org back online. If you have the newest version of dat (7.0.2) you should be able to grab it!

**Comment by karissa** [comment]
--skim doesn't work, though.
