### ISSUE TITLE
How to prevent `dat init` from prompting

### ISSUE THREAD

**Issue by rjsteinert** [maxogden/dat#358]
Looking at [line 80 of init-dat.js](https://github.com/maxogden/dat/blob/master/lib/util/init-dat.js#L80), it looks like there is a way to prevent `dat init` from prompting... Am I on the right track? This is important for me to be able to automate the creation of dat datasets.

**Comment by mafintosh** [comment]
`dat init --no-prompt` should do the trick. could you try that and see if that works for you?

**Comment by rjsteinert** [comment]
w00t! That did the trick. Greping around I see the `no-prompt` option is documented in the `destroy` command. Also being used in the tests which makes sense, should have thought to look there. I'm not sure how support for `no-prompt` is tied in there though. 

```
 /.../rjsteinert/dat[master] ♘ grep -rn 'no-prompt' ./
.//docs/cli-docs.md:456:$ dat destroy [--no-prompt]
.//docs/cli-docs.md:463:- `no-prompt` - add this flag to skip the prompt and force the destroy
.//tests/helpers/index.js:28:  test('helpers: init a dat (--no-prompt)', function (t) {
.//tests/helpers/index.js:30:    var st = spawn(t, dat + ' init --no-prompt', {cwd: datPath})
.//tests/json.js:75:  var st = spawn(t, dat + ' destroy --no-prompt --json --path=' + dat1, {cwd: tmp, end: false})
.//tests/json.js:79:    helpers.exec(dat + ' init --no-prompt --path=' + dat1, {cwd: tmp}, function (err, out) {
.//usage/destroy.txt:7:--no-prompt      destroy without prompting
```

**Comment by mafintosh** [comment]
In general you can negate all boolean flags by adding `--no-` infront.

**Comment by rjsteinert** [comment]
Interesting! Thanks for the tip.

**Comment by maxogden** [comment]
I added it to the usage docs https://github.com/maxogden/dat/commit/347f07c18e1869d75064a02340ddd651da3c2815
