### ISSUE TITLE
Readme needs a quick start

### ISSUE THREAD

**Issue by mlissner** [maxogden/dat#364]
I've checked out dat a few times now, but I don't really get it. I read the readme and then I took a look at the command listing, but I want to see some use cases that say, "you have x you want to share with the world, but you can't because of y. Well, with dat you can fix this by running command z."

From tweets and such I get the impression that I should pay attention to dat since I work with data all day, but the readme doesn't make it at all clear what problems it solves or how to dive in.

**Comment by waldoj** [comment]
:+1: I think a new screencast is probably in order, too.

**Comment by karissa** [comment]
Yes @mlissner, on it!

**Comment by waldoj** [comment]
Yay! You're welcome to assign work to me on that, too. I'm in no position to start it from scratch, but happy to contribute/edit/whatever.

**Comment by karissa** [comment]
@waldoj we are using https://github.com/maxogden/get-dat as our tutorial. It'd be a great help if you have time to go through and edit/update as needed

**Comment by waldoj** [comment]
:+1:

**Comment by mlissner** [comment]
This is a big improvement. Thanks for this. Just the link to try-dat is useful (maybe I missed it before?) 

Anyway, looks like dat is probably more for scientists and people working/generating data than it is for me. It's interesting though. It's something like a versioned database with branching? I wonder if a description like that would be useful for folks.
