### ISSUE TITLE
Issues with fat32?

### ISSUE THREAD

**Issue by rjsteinert** [maxogden/dat#365]
Hi all - 
Has anyone noticed issues on fat32 filesystems? When trying to `dat init` on a fat32 USB drive from both Debian on Raspberry Pi and Mac OS I get errors.

<img width="1184" alt="screen shot 2015-07-31 at 1 21 42 am" src="https://cloud.githubusercontent.com/assets/156575/9001491/32e9c264-3726-11e5-90f0-fc6bd0193c02.png">

<img width="737" alt="screen shot 2015-07-31 at 1 21 31 am" src="https://cloud.githubusercontent.com/assets/156575/9001496/393e0c60-3726-11e5-9a49-34d34301f79e.png">

But when the USB drive is ext4, there is no problem.  

Looking inside `data.dat`, @treehouse-su noticed some things with sticky bits which wont play nicely on fat32.

```
srwxr-xr-x  1 root root    0 Jul 31 05:44 dat.sock
```

**Comment by mafintosh** [comment]
Interesting... This is probably related to the multiprocess stuff. I'll try to reproduce

**Comment by karissa** [comment]
wow nice catch, thanks for the bug report

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat... and it makes this issue obsolete. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
