### ISSUE TITLE
dat installation fails on prebuild --download

### ISSUE THREAD

**Issue by sboysel** [maxogden/dat#374]
Hello all,

Following up an issue I mentioned in IRC.  `prebuild --download` fails when installing dat from either `sudo npm install dat -g` or `sudo npm install -g` in the cloned repo.

    > leveldown@1.4.0 install /usr/lib/node_modules/dat/node_modules/dat-core/node_modules/leveldown
    > prebuild --download

    prebuild http request GET https://github.com/level/leveldown/releases/download/v1.4.0/leveldown-v1.4.0-node-v14-linux-x64.tar.gz
    prebuild WARN install EACCES, open '/root/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.4.0-leveldown-v1.4.0-node-v14-linux-x64.tar.gz.15808-25ec8c26.tmp'
    prebuild info install Could not install prebuild. Falling back to compilation
    prebuild ERR! build EACCES, mkdir '/root/.node-gyp/0.12.7/deps/http_parser'

Some system specs:

    > uname -a
    Linux archbook 4.1.4-1-ARCH #1 SMP PREEMPT Mon Aug 3 21:30:37 UTC 2015 x86_64 GNU/Linux

    > node --version
    v0.12.7

    > npm --version
    2.13.2

I'm a complete nodejs novice but I'm willing to help troubleshoot in any way I can.

**Comment by mafintosh** [comment]
Are you running this as root?

**Comment by sboysel** [comment]
@mafintosh yes.

**Comment by dela3499** [comment]
I seem to run into this issue as well.

**Comment by miishke** [comment]
The same issue here.

**Comment by mafintosh** [comment]
could you try running this with `--unsafe-perm` to see if that makes a difference?

**Comment by miishke** [comment]
@mafintosh It worked! Too tired to test thoroughly, but repo init works.

**Comment by sboysel** [comment]
Works for me as well.  Thanks @mafintosh !

**Comment by miishke** [comment]
I see this has been reopened. If it helps, I had the same issue on Linux first, and then today on OS X. Both have been resolved with `--unsafe-perm`.

**Comment by karissa** [comment]
Thanks @miishke ! I just re-opened it so people can find it if they're also having trouble. Going to add it to the readme, too.

**Comment by karissa** [comment]
OK I added this to the readme

**Comment by jekrb** [comment]
Fails to install on io.js -v3.0.0 even with --unsafe-perm

Pretty sure it's the same issue as Level/leveldown#211
