### ISSUE TITLE
Adding blob by URL fails

### ISSUE THREAD

**Issue by waldoj** [maxogden/dat#379]
Stepping through [the get-dat guide](https://github.com/waldoj/get-dat/blob/master/markdown/04-working-with-files.md), I was surprised that running this failed:

```
dat write http://try-dat.com/static/img/wildcat.jpg -m "Added a wildcat because I can."
Error: File at http://try-dat.com/static/img/wildcat.jpg does not exist
```

The file does, in fact, exist:

```
$ curl --head http://try-dat.com/static/img/wildcat.jpg
HTTP/1.1 302 Found
Connection: close
Pragma: no-cache
cache-control: no-cache
Location: /static/img/wildcat.jpg
```

I don't know this, but I speculate that the problem is that the server returns a 302, instead of a 200.

**Comment by waldoj** [comment]
I just tried an image from another server that returns a 200. That also didn't work. So I've got nothin'.

**Comment by karissa** [comment]
Try now Waldo, I was waiting on mafintosh to update the docker image

**Comment by karissa** [comment]
He just pushed it at 437pm est

**Comment by waldoj** [comment]
I don't know enough about npm to know how to install the latest version of dat from GitHub. ¯\\\_(ツ)\_/¯

**Comment by karissa** [comment]
Oh we should probably have a thing in the readme about updating dat from npm. It has been pushed to npm, though, so you should be able to do 
```
npm install dat --upgrade
```

As far as getting the latest development version, it's pretty easy (compared to a lot of python projects I've worked with!) If you look at the readme under 'Developers' at the end, you should be able to do that on a mac or linux box. Let me know if you have trouble

**Comment by karissa** [comment]
edit: originally had forgotten the -g flag

**Comment by karissa** [comment]
This seems fixed on http://try-dat.com
