### ISSUE TITLE
MySQL backend

### ISSUE THREAD

**Issue by cshum** [maxogden/dat#384]
I am looking into implement MySQL backend for Dat/LevelUP. 

Since Sublevel mimics ’table’ feature and MySQL has already got tables, it sounds a bit silly and suboptimal to implement Sublevels on top of single MySQL table. 

My attempt of MySQL backend [MyDOWN](https://github.com/cshum/mydown) is to expose a LevelDOWN compatible factory, where `levelup()` specifies table as location argument:

```js
//DOWN factory
var mydown = require('mydown')('db', {
  user : 'root',
  password : 'secret'
}); 
//tables a, b as levelup
var a = levelup('a', {db: mydown });
var b = levelup('b', {db: mydown });

a.batch([
  { type: 'put', key: 'foo', value: 'a' },
  { type: 'put', key: 'foo', value: 'b', prefix: b }, //cross tables
], function(){
  a.get('foo', function(err, val){
   //val === 'a'
  });
  b.get('foo', function(err, val){
   //val === 'b'
  });
});
```
`batch()` is a transactional and operations can be applied into multiple tables using `options.prefix`, 
the question remains is how these should be wrapped into the current Sublevel implementation.

What do you guys think?

**Comment by mafintosh** [comment]
Is it possible to do transactions across tables (sublevels)? We require this for on disk consistency currently

**Comment by cshum** [comment]
The above `batch()` actually translates into SQL transaction statement:
```sql
START TRANSACTION;
INSERT INTO `a` SET `key` = 'foo', `value` = 'a' ON DUPLICATE KEY UPDATE `key` = 'foo', `value` = 'a';
INSERT INTO `b` SET `key` = 'foo', `value` = 'b' ON DUPLICATE KEY UPDATE `key` = 'foo', `value` = 'b';
COMMIT;
```
The [InnoDB](http://dev.mysql.com/doc/refman/5.1/en/innodb-transaction-model.html) storage engine it is currently using, is relatively robust and does support transactions across tables. Not the case for MyISAM engine, however.

**Comment by cshum** [comment]
Trying to wrap these up as much as I could [SublevelUP](https://github.com/cshum/sublevelup).

Normal sublevel
```js
var level = require('level');
var sublevelup = require('sublevelup');

var sub = sublevelup(level('./db'));

var hello     = sub('hello'); //prefix !hello!
var foo       = sub('foo'); //prefix !foo!
var fooBar    = sub(foo, 'bar'); //prefix !foo#bar!
var fooBarBla = sub(fooBar, 'bla'); //prefix !foo#bar#bla!
```

MySQL sublevel
```js
var mydown = require('mydown');

var sub = sublevelup(mydown('db', {
  host:     'localhost',
  user:     'root',
  password: 'secret'
}));

var hello     = sub('hello'); //table hello
var foo       = sub('foo'); //table foo
var fooBar    = sub(foo, 'bar'); //table foo_bar
var fooBarBla = sub(fooBar, 'bla'); //table foo_bar_bla
```

**Comment by karissa** [comment]
Have you seen calvinmetcalf/sqldown? Maybe he would have insight

**Comment by karissa** [comment]
@cshum any luck with this ?

**Comment by karissa** [comment]
@cshum ohh just saw your PR. cool.

**Comment by karissa** [comment]
Thanks for trying out dat beta and submitting an issue. After a whole year of feedback from the community, we recently published a new version of dat... and it makes this issue obsolete. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
