### ISSUE TITLE
-d={name} does not parse

### ISSUE THREAD

**Issue by mafintosh** [maxogden/dat#385]
When specifying a dataset using the following syntax

```
dat export -d=test
```

the dataset gets parsed as `=test`

**Comment by karissa** [comment]
sad

**Comment by karissa** [comment]
is this a minimist issue though?

**Comment by karissa** [comment]
opened a PR for minimist https://github.com/substack/minimist/pull/62

**Comment by karissa** [comment]
waiting on https://github.com/maxogden/subcommand/pull/4
