### ISSUE TITLE
Standalone electron app

### ISSUE THREAD

**Issue by karissa** [maxogden/dat#389]
Users should not be expected to use git with dat. As such, we can begin to prioritize use cases in social sciences, where command line tools are not commonly adoptable. 

We should create an easy-to-use standalone cross-platform app for dat using electron or a custom chromium build. In this way, we would replace the use of Dropbox/Google Drive/email in the social sciences to collaborate on their code and data.

**Comment by onbjerg** [comment]
what would this mean? "just" listen for file changes and put them in dat? push/pull buttons and multiple dats in an interface? automatic syncing?

so many questions

**Comment by karissa** [comment]
Right now we're going to do something really simple. Each dat is a folder. In the app, you will be able to track what folders you have. We are going to integrate BitTorrent, so you can seed it directly from your computer. The Electron app will be more like a torrent client than a github app, in that case

**Comment by onbjerg** [comment]
how would this help me as a less technical user? i would still have to use the cli for dat-related things, no?

**Comment by karissa** [comment]
For the coming weeks, yes. But in the long term, we can evolve this app to be more full-featured.

**Comment by karissa** [comment]
Http://github.com/Karissa/dat-app
