### ISSUE TITLE
static dump of a dat

### ISSUE THREAD

**Issue by karissa** [maxogden/dat#392]
After convo with @talos, seems wise to have a 'dat dump' , that is, a binary version of a dat that could be packaged and stored on s3 or some place, from where another dat can `dat pull`.

This is particularly useful in cases where a producer doesn't have the server resources/capacity to host a bunch of dats, or when a dat needs to be transferred from one place to another

**Comment by talos** [comment]
:+1:

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat... and it makes this issue obsolete. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
