### ISSUE TITLE
No data saved when import is cancelled

### ISSUE THREAD

**Issue by karissa** [maxogden/dat#394]
Start importing a large file, then cancel it. It seems like the data is gone. Is this the desired behavior?

```
taxi-data $ curl  -s 'http://www.opendatacache.com/data.cityofnewyork.us/api/views/gkne-dk5s/rows.csv' | gunzip -c | dat import - -d taxis
Wrote [+76563, -0].
^C
taxi-data $ dat datasets
files
taxi-data $ dat status
Current version is b152aac88d4f74d15a85c01c4d99b023aec2d362e2315853d6711934c0353d1e (latest)
0 datasets, 0 keys, 1 file, 1 version, 224 B total
Last updated just now (Wed Sep 02 2015 10:59:18 GMT-0400 (EDT))
taxi-data $ dat forks
b152aac88d4f74d15a85c01c4d99b023aec2d362e2315853d6711934c0353d1e
```

**Comment by mafintosh** [comment]
This is happening because the entire write is an transaction, https://github.com/maxogden/dat-core/issues/17

**Comment by mafintosh** [comment]
The transaction can be disabled by making this configurable, https://github.com/maxogden/dat/blob/ce996eaf3a7e5be4eb39dc6533d786d1112553c5/lib/import.js#L36

**Comment by karissa** [comment]
Aren't there other programs where if you ^C, it'll ask you a question? (not kill -9) We could ask if the user wants to keep the data or not.

Or we could put it on a fork.

Or we need another abstraction like git 'commits' ... just ideas

**Comment by Juul** [comment]
How about ^C stops the program with a message: "Interrupted before import could complete. Remove partially imported data with 'dat clean' or complete import by re-running the previous import command".

**Comment by maxogden** [comment]
The confusing thing here is that the data is saved to disk, dat just doesn't know about it because its in an inconsistent state. I think we can detect incomplete transactions (ones that never had an 'end' saved to disk) and be able to at least find + remove them efficiently with a `dat clean`, right @mafintosh?

**Comment by karissa** [comment]
Right. It'd be nice to be able to see that data and use it as a data sample, though. If its on a fork, at least, that'd be awesome. If I could then `dat undo`, that'd do the trick (dat clean would remove other data too, might not be ideal.)

**Comment by maxogden** [comment]
Agree `dat undo` could fix it, though I wonder what happens when your dat crashes during import and you *dont* do `dat undo` and then do another import
