### ISSUE TITLE
Discrepancy in the counter for the number of written records

### ISSUE THREAD

**Issue by amit-chavan** [maxogden/dat#409]
Hi,
`dat import` shows the number of records added/deleted. Eg:
```bash
~/test/dat $ dat import -d restaurant r.csv 
Wrote [+494299, -0].
Done importing data. 
Version: 4ba5815a2d2876dce68b0069ec9626d599abb28e713de134ed805c9199693353
```
However, `dat log` shows different counter values for the same commit.
```bash
Version: 4ba5815a2d2876dce68b0069ec9626d599abb28e713de134ed805c9199693353 [+492020, -0]
Date: Wed Sep 23 2015 16:49:00 GMT-0400 (EDT)
```

For reference, the CSV file I used is available here: [NYC Restaurant Inspection Scores](https://nycopendata.socrata.com/Health/DOHMH-New-York-City-Restaurant-Inspection-Results/xx67-kt59). Am I missing something here?

**Comment by maxogden** [comment]
@amit-chavan thanks for the bug report

I am able to reproduce, I downloaded the CSV and got these results:

```
~/Downloads/rest 🐈  dat init
name: (rest) 
description: (N/A) 
publisher: (N/A) 
Initialized a new dat at /Users/max/Downloads/rest
~/Downloads/rest 🐈  dat import DOHMH_New_York_City_Restaurant_Inspection_Results.csv -d inspections
Wrote [+494553, -0].
Done importing data. 
Version: ab016ed07579f8cdf52856999856fc02fb48dada92eb3a66db84e7a36be80644
```

when I check the number of lines in the csv I get 1 more than what my import progress showed:

```
~/Downloads/rest 🐈  wc -l DOHMH_New_York_City_Restaurant_Inspection_Results.csv 
  494554 DOHMH_New_York_City_Restaurant_Inspection_Results.csv
```

however my `dat log` shows 494553:

```
Version: ab016ed07579f8cdf52856999856fc02fb48dada92eb3a66db84e7a36be80644 [+491326, -0]
Date: Thu Sep 24 2015 09:55:47 GMT-0700 (PDT)
```

however doing `dat export -d inspections | wc -l` returns the right number:

```
at export -d inspections | wc -l
  494553
```

so it appears the bug is related to how to store the number in the `dat log`

**Comment by ekg** [comment]
@maxogden I am loving your prompt.

**Comment by karissa** [comment]
Thanks for trying out dat beta and submitting an issue. After a whole year of feedback from the community, we recently published a new version of dat... and it makes this issue obsolete. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
