### ISSUE TITLE
serve multiple dat repositories from a single server

### ISSUE THREAD

**Issue by corbt** [maxogden/dat#41]
I'm working on an open source Github-for-dat project called [DatRepo](https://github.com/kcorbitt/datrepo). The idea is that users will be able to upload, download, search and share datasets easily.

My question is whether there is a vision/roadmap for serving multiple dat repositories from a single machine. I can think of at least three different implementations.

  1. The most trivial approach would be to run a separate instance of the dat server on a unique port for each repository. This has the big advantage of simplicity. However, for a server with hundreds or thousands of repositories I'm not sure that this will scale very well, despite node's light footprint. 
  2. A more complex solution would be to have a single dat server per machine, and calls to "dat serve" would simply register the current dat directory with the server in a unique namespace. So "dat serve --namespace my_data" could activate the routes "localhost:6461/my_data/_package", etc. This approach seems scalable and in the ethos of dat to me, and it's my preferred solution.
  3. Alternatively, dat could mimic git's paradigm and not mount a server on the remote at all, instead just piggybacking on SSH and having the local dat client connect to the remote filesystem and synchronize that way. I don't think that this is a good idea.

Are any of these, or an alternative, likely to become part of the dat protocol? Is there a reason why supporting multiple repositories on a single machine is a bad idea?

**Comment by karissa** [comment]
We now support multiple datasets in dat beta. We also piggyback on ssh/http now, although there's still a simple dat server in core that allows for syncing and replication. I think we can close this now, thanks for all the discussion and input!

There are a bunch of open issues so if you think you want to keep chugging on this, we could use more input and hands! :)
