### ISSUE TITLE
Pushing to an empty dat repo results in 2 forks instead of one

### ISSUE THREAD

**Issue by flyingzumwalt** [maxogden/dat#410]
I assumed that dat would work like git here but it doesn't, so I'm submitting a ticket/question to call out the discrepancy.

## Scenario
I have a local dat repo with one dataset fork.  I want to set up that dat repo on a server.  There is not a copy of the repo on the server yet.  

## How do I put it there?  

When I run `dat status` in my local repo I see 1 fork with 5 versions of 1 dataset

    $ dat status
    Current version is 04f89a2e93e449c774a19819b032af5e5f7ec1ec66cd03427af3023eb351679e (latest)
    1 dataset, 8880 keys, 1 file, 1 fork, 5 versions, 6.85 MB total
    Last updated 4 days ago (Sun Oct 11 2015 11:29:27 GMT-0700 (PDT))

I want to replicate that onto the server so on the server I run 

    $ cd /the_dat_repo
    $ dat init

Then on my local machine I run

     $ dat push ssh://my.server.com:/the_dat_repo  

Now i expect my remote dat repo to look identical to my local repo.  Instead I get 2 forks on the server.  Running `dat status` on the server looks like this:

    $ dat status
    Current version is f8c1600f1653307a3f5d48cc4e7d037f3b13303ed9db5996314dd9dbf29d859e (latest)
    0 datasets, 0 keys, 1 file, 2 forks, 1 version, 383 B total
    Last updated 33 minutes ago (Thu Oct 15 2015 23:05:10 GMT+0000 (UTC))

On the local machine when I run `dat forks` I get one fork:  

    $ dat forks
    04f89a2e93e449c774a19819b032af5e5f7ec1ec66cd03427af3023eb351679e

but on the server it returns two:

    $ dat forks
    04f89a2e93e449c774a19819b032af5e5f7ec1ec66cd03427af3023eb351679e
    f8c1600f1653307a3f5d48cc4e7d037f3b13303ed9db5996314dd9dbf29d859e

**Question**: Is this the intended behavior?
**Question**: What is the best way to get a clean copy of a repository onto a server? Should I sftp it?
**Question** Is it possible to edit your dat commit history?  ie. Throw away the fork at  f8c1600f1653307a3f5d48cc4e7d037f3b13303ed9db5996314dd9dbf29d859e?

**Comment by maxogden** [comment]
@flyingzumwalt HMM that is weird. @mafintosh do you have ideas on why it didn't replicate correctly?

**Comment by karissa** [comment]
@flyingzumwalt I think this happened because you did 'dat init' on both sides, so there were two heads! Ideally you'd `dat init` on the server side and then `dat clone` from the client. Does that make sense?

**Comment by flyingzumwalt** [comment]
@karissa your answer helped me understand how to pose this as a ticket/suggestion instead of a question.  I'm closing this issue and replacing it with #411.
