### ISSUE TITLE
dat init should not create an empty HEAD

### ISSUE THREAD

**Issue by flyingzumwalt** [maxogden/dat#411]
# Scenario

Ronda Researcher has a dat repository that she's been putting data into for days.  Now she wants to share the data on dat.datalove.com 

# How this should work

1. Ronda tells dat.datalove.com to create an empty dat repo at dat.datalove.com/ronda/high_scores
2. Ronda pushes from her local dat repo to http://dat.datalove.com/ronda/high_scores

This kind of flow is possible with git but not currently possible with dat because `dat init` creates an empty, unnecessary head.

# Why: The empty head gets in the way

## How it works with git

unlike dat, `git init` does not create an initial commit.  

    $ git init
    Initialized empty Git repository in /Users/matt/foo/.git/
    $ git log
    fatal: bad default revision 'HEAD'

There is nothing in the log (no HEAD) until you commit something.

    $ touch README.md
    $ git add README.md
    $ git commit -m"Initial Commit"
    [master (root-commit) eded6ee] Initial Commit
     1 file changed, 0 insertions(+), 0 deletions(-)
     create mode 100644 README.md
    $ git log
    commit eded6ee37f7d9b160f3dad57ed4675d220ddc413
    Author: Ronda Researcher <ronda@research.com>
    Date:   Fri Oct 16 11:08:40 2015 -0700

        Initial Commit

## How it works with dat 

By contrast, dat creates an empty version when you run `dat init`

    $ dat init
    name: (foo) 
    description: (NA) 
    publisher: (NA) 
    Initialized a new dat at /Users/ronda/foo
    $ dat log
    Version: 424a463d9a400fa5aa9b1a35284130852dfc584e206253cfd9b403175a3877d2 [+1, -0]
    Date: Fri Oct 16 2015 11:12:38 GMT-0700 (PDT)

Because of this, when Ronda pushes her data to http://dat.datalove.com/ronda/high_scores she gets two heads -- the empty unwanted one and the one that actually has her data in it.  This means that in order to get her pre-existing data from a local dat repository onto a server she has to 

1. Tell dat.datalove.com to create an empty dat repo at dat.datalove.com/ronda/high_scores
1. Run `dat replicate http://dat.datalove.com/ronda/high_scores` (or clone from there and push to the local clone)
2. merge the _real_ head with the unnecessary head, resulting in a misleading history in `dat log`
3. Push the merged data to http://dat.datalove.com/ronda/high_scores

Though this just 2 extra steps, they're unintuitive, mildly error-prone, and don't create any value -- they're purely workarounds for the fact that `dat init` created an unwanted HEAD.

**Comment by karissa** [comment]
@flyingzumwalt thanks so much for spending the time detailing this out. We are currently in the process of moving to http://github.com/mafintosh/dat-graph, and in that implementation, dat won't create the root node for you -- it'll take the first one you add as the root. Hurray!

**Comment by flyingzumwalt** [comment]
Awesome! Closing this ticket then.
