### ISSUE TITLE
Track committer and author

### ISSUE THREAD

**Issue by flyingzumwalt** [maxogden/dat#413]
dat should, track committer and author like git.  Even if it doesn't set them by default, allow users to pass in the values with `--committer`, and `--author` flags and store the values in leveldb as `"committer"` and `"author"`

An import like this

`dat import proteins.csv -d proteins --committer "C O Mmitter <committer@example.com>"  --author "A U Thor <author@example.com>"`

Would result in rows that look like this
```json
{
    "content":"row",
    "key":"cifvfaopm000wflaecmb9k1gl",
    "version":"04c3301367d351bae0e8bb12bb8b15e9d0a025932d678282edb6b076097475fb",
    "committer":"C O Mmitter <committer@example.com>",
    "author":"A U Thor <author@example.com>",
    "value":{...data...}
}
```

and entries in the dat log like this:
```
Version: 04c3301367d351bae0e8bb12bb8b15e9d0a025932d678282edb6b076097475fb [+1, -0]
Author: "A U Thor <author@example.com>"
Date: Thu Oct 22 2015 12:23:13 GMT-0700 (PDT)
```

## Why both author and committer?

The [git book]() explains
> The author is the person who originally wrote the work, whereas the committer is the person who last applied the work. So, if you send in a patch to a project and one of the core members applies the patch, both of you get credit – you as the author, and the core member as the committer.

related to #121

**Comment by karissa** [comment]
This is a great idea. This should be implemented as metadata in the `{message: opts.message}` part of bin/import.js and bin/write.js. Right now, it just turns it into a buffer and saves it. Instead, if it was stored as json, it could be then decoded to the cli as 'author' and 'commitor' and 'message' in bin/log.js. What do you think?

**Comment by flyingzumwalt** [comment]
Yeah. Including the message in cli output is a good idea.  It's already included in the output for `dat log --json`

Is there already a way, from the CLI, to provide extra stuff to put in that metadata? That would at least let me record author/committer even if the cli doesn't explicitly support it yet.

**Comment by onbjerg** [comment]
I like this idea. How would dat go about filling it in automagically?

I was thinking that you could add the defaults to .dat.yml (if that is accepted, described in #416), such that it would now look like

```yml
remote: http://my.dat.edu
ignore:
  - data.dat
  - .git
comitter:
  - name: C. O. Mitter
  - email: comitter@example.com
```

And then you would pass in the ``--author`` if necessary. I think this would require the ignores to be in a seperate file, though

**Comment by onbjerg** [comment]
@karissa I tried modifying my local dat a bit (with a naïve approach) to include comitter and author, but it seems like you can't just change ``{message:opts.message}`` to something like

```
{
    message: {
        body: opts.message,
        author: opts.author,
        committer: opts.committer
    }
}
```

as dat-core requires it to be a string so it can convert it to a buffer. So either a) dat-core needs to be changed to accomodate author and committer, or b) we need to encode the author, committer and message into one string

**Comment by karissa** [comment]
@onbjerg wow great work! We are currently actually rewriting dat, I sent you an email, did you get it? (maybe it was the wrong person?)

Check out the branch here: https://github.com/maxogden/dat/tree/1.0

Most of the work is being done in other modules currently, but author/committer will totally be in there.

**Comment by onbjerg** [comment]
@karissa oh yes, I received the e-mail and I've left a reply

the branch is like almost entirely empty, so i figure you're starting from semi-scratch again? is this the same for dat-core?

**Comment by karissa** [comment]
@onbjerg yeah, dat-core will actually be replaced by github.com/mafintosh/hypergraph and github.com/mafintosh/hyperdrive (in development)

**Comment by onbjerg** [comment]
@karissa damn you guys have a lot of stuff to do

**Comment by karissa** [comment]
We recently published a new version of dat that makes this issue obsolete. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
