### ISSUE TITLE
Installed DAT, ran tutorial, versioning and checkouts didn't work

### ISSUE THREAD

**Issue by libertytrooper** [maxogden/dat#420]
Installed dat via NPM. (npm install -g dat).  Proceeded through tutorial.  None of the functionality other than initial checkin worked.

**Comment by karissa** [comment]
Sorry it isn't clear in the read me, but dat is currently undergoing a rewrite and is in an unstable phase. Please sign up for our tiny letter on dat-data.com for updates. I'll add some language to this affect soon!

**Comment by karissa** [comment]
What error did you get @libertytrooper ? did you check troubleshooting on the readme?
