### ISSUE TITLE
Listing the versions of a specific dataset.

### ISSUE THREAD

**Issue by nessyhamsa** [maxogden/dat#422]
Hi, 
I had gone through the features of Dat, it looks nice and interesting. I faced an issue when i was trying to list the versions of datasets. Imported two different files to two different datasets in a dat repository, when I list the log using <code>dat log</code> command, all versions in the dat repository are listed. 
Is there any option for taking the versions of a specific dataset?

**Comment by karissa** [comment]
Hey @nessyhamsa!

Every time dat takes a snapshot of the data, it saves all of it at once. You can think of a dataset as a file -- and we don't have the capability to go back in time on just files right now. This is a great feature idea though, and I think other people want it too. Thank you!

**Comment by nessyhamsa** [comment]
Can u please provide a way to get the dataset name used for each version during file import along with log details. 
It seems currently the log object contains below details.
{ root: false,
  change: 42,
  date: Wed Dec 09 2015 14:10:41 GMT+0530 (IST),
  version: 'b2df5855c3627753a0776a4c7a7751115fca2e9dbed96511f96d29a9d44e0631',
  message: '',
  links: [ '7c4af74e78a797ae7f18c9cb589176bd874d09eeed90bfb8906719ce6494e48c' ],
  puts: 3,
  deletes: 0,
  files: 0 }
We just need a dataset along with these details. 
We didn't identified from which JS in dat folder updating these details at the time of file import.
