### ISSUE TITLE
Filtering the log based on a dataset

### ISSUE THREAD

**Issue by febinjoy** [maxogden/dat#423]
As Dat keep the versions for a repository, I found it hard to quickly know the versions in which a particular dataset had a change. I tried making few changes to the dat-core to add dataset name also along with the below structure.

    {
        root : false,
        change : 42,
        date : Wed Dec 09 2015 14 : 10 : 41 GMT + 0530(IST),
        version : 'b2df5855c3627753a0776a4c7a7751115fca2e9dbed96511f96d29a9d44e0631',
        message : '',
        links : ['7c4af74e78a797ae7f18c9cb589176bd874d09eeed90bfb8906719ce6494e48c'],
        puts : 3,
        deletes : 0,
        files : 0,
        dataset : 'myDataset'
    }

This helps to store the changed dataset for each version the user commit. 

I added an optional parameter -d to the log command so that the user can filter the log for a particular dataset.

**Comment by karissa** [comment]
Thanks for trying out dat beta and submitting an issue. After a whole year of feedback from the community, we recently published a new version of dat... and it makes this issue obsolete. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
