### ISSUE TITLE
dat status showing confusing number of keys

### ISSUE THREAD

**Issue by finnp** [maxogden/dat#425]
Hey,

I just was a bit confused, because `dat status` showed that my dataset had `269898` keys, when I expected it to be `100000`. I suppose what the higher number means is the number of rows with all versions? If so calling it `keys` is a bit confusing.

```
➜  berlin-trees  dat keys -d anlagenbaeume | wc -l
  100000
➜  berlin-trees  dat status
Current version is 35ea8f17da090680ed1629a3623e3151b05c82b864c154eefe8080e1e8d67c49 (latest)
1 dataset, 269898 keys, 1 file, 1 fork, 1690 versions, 106.96 MB total
Last updated 22 hours ago (Thu Dec 17 2015 23:56:48 GMT+0100 (CET))
➜  berlin-trees  dat datasets
anlagenbaeume
```

https://github.com/maxogden/dat/blob/master/bin/status.js#L30

**Comment by karissa** [comment]
Thanks for trying out dat beta and submitting an issue. After a whole year of feedback from the community, we recently published a new version of dat... and it makes this issue obsolete. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
