### ISSUE TITLE
create subdirectories when non-existent path is specified

### ISSUE THREAD

**Issue by joehand** [maxogden/dat#438]
If you try to download into a non-existent path, Dat fails: 

```bash
$ dat dat://link --path='/some/fake/dir'
Does not exist: /some/fake/dir
```

Dat should create the directories instead of failing.

**Comment by maxogden** [comment]
Do you think it should:

- Just create it
- Prompt `Does not exist: /some/fake/dir, would you like to create it (y/n):` (or pass `-y` to say yes to everything like how apt-get works)

**Comment by joehand** [comment]
Prompting seems like the better solution, just in case someone is downloading in the wrong place (thinking a path existed but it didn't).

**Comment by karissa** [comment]
+1 prompting

**Comment by mafintosh** [comment]
https://www.youtube.com/watch?v=ussCHoQttyQ
