### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by jqnatividad** [maxogden/dat#439]
Is there a mechanism that can be leveraged to track usage of published data?

Ideally, this would integrate into something free and in widespread use like Google Analytics.  Perhaps, leveraging its [Event Tracking] (https://developers.google.com/analytics/devguides/collection/analyticsjs/events) capabilities?

**Comment by karissa** [comment]
Oh yeah, this is a great idea. 

This doesn't exist yet, but I imagine it'd be useful. If someone wants to take a look at this, it might be good to first look at `fs.js` at the `createDownloadStream` method. One could implement an external module to track downloads. It could also listen for the `peer` method if you just want to track # of people downloading.

**Comment by joehand** [comment]
This is a project we'd like to do. Please track progress here: https://github.com/datproject/projects/issues/4. 

Thanks!
