### ISSUE TITLE
If the terminal is not very wide, 'connected to x sources' prints forever.

### ISSUE THREAD

**Issue by karissa** [maxogden/dat#450]
```
...
  [Done] styles/SourceSansPro-BoldIt.otf
  [Done] styles/SourceSansPro-Bold.otf
  [Done] styles/SourceSansPro-BlackIt.otf
  [Done] styles/SourceSansPro-Black.otf
  [Done] styles/SIL Open Font License.txt
[Done] Files Read to Dat: 81 of 81 (1.47 MB of 1.47 MB)
[Status] Connected to 0 sources
[Status] Connected to 0 sources
[Status] Connected to 0 sources
[Status] Connected to 0 sources
[Status] Connected to 0 sources
[Status] Connected to 0 sources
[Status] Connected to 0 sources
[Status] Connected to 0 sources
[Sharing] dat://33e5eec886d17e10f67f726485d1533369d9926335174e4ed2a27495b908afd0^C
styles $
```

**Comment by karissa** [comment]
@mafintosh says he knows how to fix it

**Comment by karissa** [comment]
you have to detect that the link that is printed at the end is two lines, it assumes it is on one line

**Comment by mafintosh** [comment]
`process.stdout.columns` contains the width of the terminal. if what is less than the line width this will happen

**Comment by mafintosh** [comment]
maybe we can fix this in single-line-log actually ...

**Comment by mafintosh** [comment]
pasting this here for future reference, https://github.com/sindresorhus/string-width

**Comment by mafintosh** [comment]
and https://github.com/tokuhirom/visualwidth-js

**Comment by joehand** [comment]
@karissa does this always show up when you have a small terminal or do you need to do something to make it happen? I can reproduce if I hit return while the process is running, but the small terminal doesn't always do it.

**Comment by karissa** [comment]
If the link is on two lines

**Comment by karissa** [comment]
here's a video https://www.dropbox.com/s/hg4dzi5jmmk72o5/terminal.mov?dl=0

**Comment by karissa** [comment]
K opened a pr over there, waiting
