### ISSUE TITLE
Dat URL listing

### ISSUE THREAD

**Issue by mateogianolio** [maxogden/dat#457]
First of all, I want to say thank you for creating this project and keeping it open-source.

Anyway, I just quickly browsed through the documentation and I'm wondering if there is a way of getting a list of `dat`'s on the current device? I could try to read from the database in the `~/.dat` folder, but I've had issues with LevelDB locking before so I thought it would be best to ask if it's even possible here first.

Something like `dat list` and it will print out a list of `dat://` urls.

**Comment by maxogden** [comment]
@mateogianolio Hi, thanks.

The LevelDB in ~/.dat is indeed where we track metadata for all the dats... but it is meant to be more of a cache than anything. So I wouldn't really trust it as a definitive source of all the dats on a machine. Whats your use case BTW?

To read the LevelDB from multiple processes we use a module called [level-party](https://npmjs.org/level-party). Also there is a module in development called dat-manager that will manage a group of dats manually. But I dont think theres an easy way we can accurately list all the dats on a machine at the moment...

**Comment by mateogianolio** [comment]
I didn't really have any specific use case in mind, but it would be neat to be able to maintain a list of dat metadata for a machine, e.g:

```
3 peers  dat://54e5c2483e06bc3403795ce62fb1df9c05a52f6e1466373425be0fc5d33ffec2
1 peer   dat://...
```

I wrote [a tiny bittorrent client](https://www.npmjs.com/package/mgnt) (unmaintained) a few months ago to learn about webtorrent and handled the inter-process communication by having the main module emit events and submodules responding to them.

The gist of what I'm looking for (in pseudo-js):

```javascript
// create new dat tcp server
var dat = new require('dat')();

dat.add('/path/to/folder');
dat.on('add', function (metadata) {
  // ...
});
dat.on('close', function () {
  // moving on...
});
```

I'll check out dat-manager and level-party.

**Comment by mateogianolio** [comment]
[dat-desk](https://github.com/karissa/dat-desk) is pretty much what I was looking to do, so I'll go ahead and close this.
