### ISSUE TITLE
idea: layers and column sets

### ISSUE THREAD

**Issue by dominictarr** [maxogden/dat#47]
I've recently had to work with some data that seems very much dat-data.
1) There is a publically available dataset that is published periodically.
2) it contains some known errors that are (manually) fixed each time an update is pulled. 3) that data is combined with another data source, essentially adding extra columns.

Given my data-replication aware viewpoint, here I think you could represent this to make it easy to replicate:

Instead of mixing it all into one spreadsheet, and versioning everything,
what about _layers_ like in photoshop? you could have the first import
as a spreadsheet on it's own - and then you could have the fixes as another
that is layed on top. This table could be very sparse - only rows with updates would be stored... and then only columns that have changes (probably leave nulls in the spaces)

It may be better to overlay the fixes, because then you can still receive updates to the original data.

Then if you pulled in data from another source you could set that beside this first 2 layer table (call this a "column set") it would add a few columns, but share the public key.

Now, you could expose these three combined tables as another table that could be exported, etc.

by separating the bits that change independently, you can greatly simplify replication - replicate base, bulk data, and then edits. replicate different sources (which update at different times, independently) as separate things.
instead of having a single commit value (version) you'd have a vector of versions (for each layer/columnset).

how does this sound?

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat. Would you mind trying out the new dat with `npm install -g dat` and see how it fits into this discussion? In the meantime, I'm going to close this issue. You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
