### ISSUE TITLE
CSV random access demo

### ISSUE THREAD

**Issue by karissa** [maxogden/dat#475]
# rationale
- github makes you download an entire csv before rendering it if the csv is too big.
- git lfs doesn't allow you to preview/render anything.
- this demo showcases that you can view data at a random byte range inside a file in dat.

# demo
- get a dat link for a folder that has a csv in it
- go to a web browser and copy that link into the app
- see the csv/click on the csv
- preview the first 50kbs. 
- type in a random page number or byte range and the page re-renders with the data from that range.

# todo
- [x] improve csv viewing for hyperdrive-ui
- [x] can choose a page number to show random access

**Comment by clkao** [comment]
This should be a good example: [Statement of Disbursements](https://www.irccloud.com/#!/irc.freenode.net:6667/%23dat) (17.3m csv)
