### ISSUE TITLE
Support Node@V6.x?

### ISSUE THREAD

**Issue by coogleyao** [maxogden/dat#477]
Support Node@V6.x?

**Comment by mafintosh** [comment]
is doesnt work on 6 now?

**Comment by coogleyao** [comment]
@mafintosh  
Node@V6.0.0 by brew install 
system: OS X EI Capitan V10.11.4
![dat in node6 not ok](https://cloud.githubusercontent.com/assets/1491058/15033189/c8823464-129a-11e6-9065-7285436a88d0.png)

**Comment by mafintosh** [comment]
could you try again? just bumped some of the dependencies

**Comment by coogleyao** [comment]
@mafintosh  ; ) Thanks!! Just like u say.
