### ISSUE TITLE
enable replication by separating mutable from immutable sections

### ISSUE THREAD

**Issue by dominictarr** [maxogden/dat#48]
You really cant do effective p2p/master-master replication without having immutable data - but on the other hand - users are used to just editing data - mutable data - just editing text files or fields.

Another tradeoff is that often mutable data is more performant - you don't have to track and recreate state from a chain of immutable appends - you just overwrite what you want to change.

Now - look at git - _internally_ git is immutable - it's based around a content addressable store of blobs, but unless the user investigates deeply, they don't encounter that. they just check out a snapshot into the _mutable section_,
aka, the working directory, where they can work on it will their an ordinary text editor.

I think the data schema dat has currently is great for a performant mutable section, but I think it will be difficult to use it for anything more than master-slave replication. And also, doesn't have the security of a hash-tree based system.
However, it would allow you make a bunch of edits, and then combine them into a commit much like git. 

Then you could send something like a patch file, and apply it on top of another table - this would just look like a csv with some metadata at the top.

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat. Would you mind trying out the new dat with `npm install -g dat` and see how it fits into this discussion? In the meantime, I'm going to close this issue. You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
