### ISSUE TITLE
[Proposal] RC2 Live & Static CLI Output

### ISSUE THREAD

**Issue by joehand** [maxogden/dat#484]
Proposal for outputs on the CLI main four functions: share live, share static, download live, download static. (cc @maxogden @mafintosh @karissa). (Continues the conversation a bit in [release rc2 issue](https://github.com/maxogden/dat/issues/476)). 

# Sharing 

## Share Live Folder
```
$ dat share .
Creating Dat: /Users/joe/node_modules/dat/tests/fixtures

  [Added] folder
  [Added] folder/empty.txt
  [Added] all_hour.csv

Files: 3  Size: 1.44 kB
[Secret Key] dccb16b2a27c603109d1ec858cb24335777522d311a31f1f614ad4b2d47e3a3b
[Status]
  Watching /Users/joe/node_modules/dat/tests/fixtures...
  Waiting for connections...
```

### Resume Share Live Folder (same directory)
```
$ dat share .
Resuming Dat: /Users/joe/node_modules/dat/tests/fixtures

  [Added] new_file.md

Files: 4  Size: 1.54 kB
[Secret Key] dccb16b2a27c603109d1ec858cb24335777522d311a31f1f614ad4b2d47e3a3b
[Status]
  Watching /Users/joe/node_modules/dat/tests/fixtures...
  Waiting for connections...
```

## Share Snapshot

*Note: Share can be done without explicit `share` command*

```
$ dat tests/fixtures --snapshot
Creating Dat: tests/fixtures

  [Added] folder
  [Added] folder/empty.txt
  [Added] all_hour.csv

Files: 2  Size: 1.44 kB
[Secret Key] 4d74013c32ce739d6c6b960c9371fe3689f6dfba23e8f88d03cc202489a3cd65
[Status]
  Dat Snapshot Finalized
  Waiting for connections...
```

# Downloading

## Download Live

```
$ dat get 75565f6283f1aa6758ef21d2e3b16aaef97413daa280c130adfd3923dff279a2 download_folder
Starting Dat: 75565f6283f1aa6758ef21d2e3b16aaef97413daa280c130adfd3923dff279a2
Downloading to: /Users/joe/Desktop/download_folder

  [Done] folder
  [Done] folder/empty.txt
  [Done] all_hour.csv

[Secret Key] 75565f6283f1aa6758ef21d2e3b16aaef97413daa280c130adfd3923dff279a2
[Completed] 3 files (1.44 kB) 
Latest Version Downloaded, Run Again to Update
(process exits)
```

## Download Snapshot

*Note: Download can be done without explicit `get` command*

```
$ dat 4d74013c32ce739d6c6b960c9371fe3689f6dfba23e8f88d03cc202489a3cd65 download_folder
Starting Dat: 4d74013c32ce739d6c6b960c9371fe3689f6dfba23e8f88d03cc202489a3cd65
Downloading to: /Users/joe/Desktop/download_folder

  [Done] folder
  [Done] folder/empty.txt
  [Done] all_hour.csv

[Secret Key] 4d74013c32ce739d6c6b960c9371fe3689f6dfba23e8f88d03cc202489a3cd65
[Completed] 3 files (1.44 kB) 
Snapshot Downloaded
(process exits)
```

**Comment by mafintosh** [comment]
Looks great. I'd make it more clear in the output that you should share "Secret Key" with your friends.

**Comment by waldoj** [comment]
Is the "secret" nomenclature (instead of "private") intended to avoid conflation with public-key cryptography terminology? A "secret" sounds like something that shouldn't be shared with anybody—I wouldn't guess that it's something that I could or should share with friends.

**Comment by joehand** [comment]
@waldoj the word was inspired by https://gist.github.com/. It's not necessarily private; if the key is shared publicly then it is no longer private (even if you don't share it). 

We should make it clearer that you *are* supposed to share that key, though maybe selectively. We could add a note similar to what gist uses: "Secret gists are hidden from search engines but visible to anyone you give the URL."

**Comment by mafintosh** [comment]
Someone like "Only users that have your dat link will be able to download your files"

**Comment by mafintosh** [comment]
@joehand How do i keep a live session open when downloading?

**Comment by joehand** [comment]
@mafintosh: @maxogden and I talked yesterday about not keeping the live connection open by default (the desktop/web may be more useful for that). If you want to update a folder via CLI you just run it again. 

I don't think a `--live` option will work on the download side, since the user won't necessarily know if a hash is live. But if we just have an option to keep download open regardless (like we did with `--seed`), that may work.

**Comment by thadguidry** [comment]
Its just a "key".  It opens doors, lockers, etc.  Keep it simple.... "key"
nothing about private, or secret...its just a key to get access. Copy the
key, you get access...share the key, they have access when they have the
key.

**Comment by joehand** [comment]
Updated language a bit from these suggestions
<img width="691" alt="screen shot 2016-06-16 at 10 02 30" src="https://cloud.githubusercontent.com/assets/684965/16128580/1ae27516-33b6-11e6-9ba2-9bab0bed027e.png">

See PR #485 for full details.
