### ISSUE TITLE
Simpler cli output

### ISSUE THREAD

**Issue by mafintosh** [maxogden/dat#491]
Was playing around with ideas to simplify the output of the cli earlier today as an experiment. The linear list of files is good at showing all files in the dat, however it is a bit verbose and makes the cli "jump up/down" once in a while. Files also aren't necessarily being downloaded linearly (the most efficient approach is "rarest first" where you sync the parts of a dat that fewest people are sharing first). 

Adding files / resuming a dat you own

```
Initializing Dat in /Users/maf/dats/test-dat.

Share link: d9ab29a1ac68d8f68921302d03562cfa6880553868f0f37e002cb6d178738cdf
The Share Link is secret and only those you share it with will be able to get the files

[=====>            ] Adding 242/2444 files (100mb/424mb)
```

Done adding files

```
Initializing Dat in /Users/maf/dats/test-dat.

Share link: d9ab29a1ac68d8f68921302d03562cfa6880553868f0f37e002cb6d178738cdf
The Share Link is secret and only those you share it with will be able to get the files

[=================>] Added 2444 files (424mb)

Uploading 142 kb/s. Watching for updates...
```

Adding live updates

```
Initializing Dat in /Users/maf/dats/test-dat.

Share link: d9ab29a1ac68d8f68921302d03562cfa6880553868f0f37e002cb6d178738cdf
The Share Link is secret and only those you share it with will be able to get the files

[=============>    ] Adding 2 updated files (40mb)

Connected to 30 peers. Uploading 142 kb/s. Watching for updates...
```

Downloading a dat from a link / re-sharing it

```
Initializing Dat in /Users/maf/dats/test-dat-clone

Share link: d9ab29a1ac68d8f68921302d03562cfa6880553868f0f37e002cb6d178738cdf
The Share Link is secret and only those you share it with will be able to get the files

[====>             ] Downloading 2444 files (100mb/424mb)

Connected to 30 peers. Downloading 442 kb/s. Uploading 142 kb/s.
```

Dat fully downloaded

```
Initializing Dat in /Users/maf/dats/test-dat-clone

Share link: d9ab29a1ac68d8f68921302d03562cfa6880553868f0f37e002cb6d178738cdf
The Share Link is secret and only those you share it with will be able to get the files

[=================>] Downloaded 2444 files (424mb)

Connected to 30 peers. All files downloaded. Uploading 142 kb/s.
```

Downloading live updated files

```
Initializing Dat in /Users/maf/dats/test-dat-clone

Share link: d9ab29a1ac68d8f68921302d03562cfa6880553868f0f37e002cb6d178738cdf
The Share Link is secret and only those you share it with will be able to get the files

[=============>    ] Downloading 2 updated files (40mb)

Connected to 30 peers. Downloading 442 kb/s. Uploading 142 kb/s.
```

**Comment by joehand** [comment]
This looks great!

**Comment by joehand** [comment]
@mafintosh a few questions:
 
1. How do we do progress for adding files? I thought we didn't know the total size until we added them.
2. Is there any way in the live archive to tell its done downloading for now? I've just been comparing downloaded files to total files but that seems weird for large live archives that are being updated.

I'll need to look at the yolowatch stuff a bit to see if we can tell how many files are being updated. Otherwise, most of this (minus progress bars) I put up on the new branch.

**Comment by mafintosh** [comment]
@joehand 

1. The stat object returned from folder-walker contains the size
2. Yea, we'll add a 'synchronized' event that'll tell you everything available has been downloaded

**Comment by karissa** [comment]
Yeah I like this minimal approach.

**Comment by maxogden** [comment]
we'll be incorporating these ideas in a future implementation
