### ISSUE TITLE
use dat-encoding

### ISSUE THREAD

**Issue by mafintosh** [maxogden/dat#492]
@juliangruber and I came up with this, https://github.com/juliangruber/dat-encoding to reduce the link size a bit. It's fully backwards compat with what we have now but links will be 50 chars instead of 64 making them valid dns subdomains

**Comment by mafintosh** [comment]
it also does link validation for us and supports potential dat.land links with a key in them

**Comment by maxogden** [comment]
should be easy to add this to this module, we just need to replace the buf.toString('hex') for the dat links with datEncoding.encode(buf), and the cli needs to use .decode(str) on input links
