### ISSUE TITLE
Use as a library?

### ISSUE THREAD

**Issue by joepie91** [maxogden/dat#495]
As it is, `dat` appears to consist of a CLI application and a number of relatively low-level dependencies that make up its functionality. The actual implementation, combining those low-level dependencies, exists within the CLI project itself.

Is there some kind of 'library version' of this that can be integrated into other applications, but without using the CLI and without having to essentially reimplement the higher-level operations? I'm pretty much just looking for a 'regular' high-level JS module.

**Comment by lukeburns** [comment]
Have you seen https://github.com/karissa/hyperdrive-archive-swarm?

**Comment by joepie91** [comment]
Hmm, I'm not sure I understand the relationship between hyperdrive and dat. Additionally, that library only seems to connect as a peer, rather than having feature parity with the `dat` CLI?

**Comment by juliangruber** [comment]
You only need a few components to get started:

- the swarm: https://github.com/karissa/hyperdrive-archive-swarm
- some leveldb implementation: https://github.com/Level/level
- hyperdrive, the core library: https://github.com/mafintosh/hyperdrive

And that's it! I'll leave stitching those libraries together as an exercise for the reader :)

**Comment by juliangruber** [comment]
> that library only seems to connect as a peer

dat is a peer to peer project, so everything is a peer. I recommend reading https://en.wikipedia.org/wiki/Peer-to-peer

**Comment by joepie91** [comment]
> dat is a peer to peer project, so everything is a peer.

Yes, I understand that. My point is that it only seems to connect as a peer that just reseeds data that is already on the network, and doesn't implement eg. upload/`share`.

> I'll leave stitching those libraries together as an exercise for the reader :)

Right. My question whether there's a pre-stitched library available - essentially doing the same as the binaries in `bin` in this repository already do, but usable as a library. Precisely to *avoid* reproducing that effort of stitching them together (and all the subsequent maintenance if/when things change)

**Comment by juliangruber** [comment]
> Yes, I understand that. My point is that it only seems to connect as a peer that just reseeds data that is already on the network, and doesn't implement eg. upload/share.

If you want to create a new archive:

```js
var archive = drive.createArchive()
```

if you want to replicate an existing one:

```js
var archive = drive.createArchive(key)
```

> Right. My question whether there's a pre-stitched library available - essentially doing the same as the binaries in bin in this repository already do, but usable as a library. Precisely to avoid reproducing that effort of stitching them together (and all the subsequent maintenance if/when things change)

There's @karissa's https://github.com/karissa/dat-manager

**Comment by karissa** [comment]
Dat-manager isn't compatible with the newest dat version

**Comment by juliangruber** [comment]
see #495

**Comment by joehand** [comment]
@joepie91 do you have an example of how you'd use it? 

Many the use cases we are trying to support will rely on either the CLI or one of the Dat apps. We've talked about having a JS library before but had trouble justifying it without knowing it'd be used (or how). Having a better idea your use case would be really helpful (and help us design the API). Thanks!

**Comment by lukeburns** [comment]
> Yes, I understand that. My point is that it only seems to connect as a peer that just reseeds data that is already on the network, and doesn't implement eg. upload/share.

@joepie91 Here's an example of sharing an archive...

```js
var hyperdrive = require('hyperdrive')
var memdb = require('memdb')
var swarm = require('hyperdrive-archive-swarm')

var drive = hyperdrive(memdb())
var archive = drive.createArchive() // create new archive

var ws = archive.createFileWriteStream('hello.txt') // add hello.txt to archive
ws.write('hello world')
ws.end()

archive.finalize(function () { // finalize the archive
  swarm(archive) // share on the swarm
  var key = archive.key.toString('hex')
  console.log(key, '<-- people with this key can download hello.txt')
})
```

And downloading the archive and writing to disk...

```js
var fs = require('fs')
var hyperdrive = require('hyperdrive')
var memdb = require('memdb')
var swarm = require('hyperdrive-archive-swarm')

var drive = hyperdrive(memdb())
var archive = drive.createArchive(key) 
swarm(archive)
archive.createFileReadStream('hello.txt').pipe(fs.createWriteStream('hello.txt'))
```

**Comment by karissa** [comment]
I think it's good to have a JS API for downloading and sharing: can we look
at the webtorrent API for inspiration? @feross presented a slick demo a
couple of weeks ago where he live coded with it.

El viernes, 24 de junio de 2016, Luke Burns <notifications@github.com>
escribió:

> Yes, I understand that. My point is that it only seems to connect as a
> peer that just reseeds data that is already on the network, and doesn't
> implement eg. upload/share.
>
> @joepie91 <https://github.com/joepie91> Here's an example of sharing an
> archive...
>
> var hyperdrive = require('hyperdrive')var memdb = require('memdb')var swarm = require('hyperdrive-archive-swarm')
> var drive = hyperdrive(memdb())var archive = drive.createArchive() // create new archive
> var ws = archive.createFileWriteStream('hello.txt') // add hello.txt to archivews.write('hello world')ws.end()
> archive.finalize(function () { // finalize the archive
>   swarm(archive) // share on the swarm
>   var key = archive.key.toString('hex')
>   console.log(key, '<-- people with this key can download hello.txt')
> })
>
> And downloading the archive and writing to disk...
>
> var fs = require('fs')var hyperdrive = require('hyperdrive')var memdb = require('memdb')var swarm = require('hyperdrive-archive-swarm')
> var drive = hyperdrive(memdb())var archive = drive.createArchive(key) swarm(archive)archive.createFileReadStream('hello.txt').pipe(fs.createWriteStream('hello.txt'))
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/maxogden/dat/issues/495#issuecomment-228397834>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAmotOe45FuqLHsHtvW5hGOUe6xno0lYks5qPAnmgaJpZM4I9dos>
> .
>


-- 
Karissa McKelvey
http://karissa.github.io/

**Comment by feross** [comment]
Thanks @karissa. If you're interested, our docs are here: https://webtorrent.io/docs
