### ISSUE TITLE
Moving the computation, not the data

### ISSUE THREAD

**Issue by groundwater** [maxogden/dat#5]
This may be completely off base for your project, but I thought I would throw it out there.

What do you think about trying to move computations closer to the data. For example, if I am maintaining a data-set with ocean temperatures, my cluster could also accept a computational payload to run on the data locally. Moving a result across the wire would be much easier than moving the entire data set.

This of course opens an whole new set of problems, but the problems may be worth the reward.

**Comment by karissa** [comment]
I think we can close this once we have #388

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat, which focuses on syncing filesystems. We are getting close to testing how to more effectively move code to data. Would you all mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
