### ISSUE TITLE
what if csv had a header with metadata?

### ISSUE THREAD

**Issue by dominictarr** [maxogden/dat#52]
for the stuff I've been thinking about recently, like diffing csv, merging and joining
it would be way easier if csv had a simple header - not just column names.
I know an hcsv file could not be opened in excel, although it could be very easy to remove the header.

just something like this. a line of `---` to demarcate the header?
``` js
----------
HEADER
----------
CSV
```

then you could have a patch file, and the header would just say which version (hash of) of the previous file it patched. You could have units for each header. You could have types for each header. You could specify which combination of columns made the primary key. You could also have this as a separate file and then load that metadata as an cli option in all the tools, but sometimes it would be much simpler to just have a header in the csv stream.

The header could be human readable, and you could easily have unix tools to parse it out.

you could also put JSON inside the header - although it might be good to use INI instead just because that is a similar legacy to CSV, so it just fits better...

**Comment by karissa** [comment]
I'm thinking we should allow people to specify a schema with a dataset. I think we can close this when we get #390 done
