### ISSUE TITLE
Security and authentication for distributed data

### ISSUE THREAD

**Issue by gmaclennan** [maxogden/dat#56]
I have been doing some thinking recently about security and authentication for distributed databases, particularly when the database is not behind a server but shared on disk, in an offline environment. I am interested in what existing thinking there is behind this and any implementations of a security model.

**Global read, restricted write**: for several use cases, in a Wikipedia/Openstreetmap type scenario, read access is not a problem but we may want to restrict editing to specific users or moderators. In a fully versioned system, users could sign any edits with a public/private key pair based on a hash of the database object edited. You could implement an index that would only look at any edits made by a group of trusted users, based on a collection of trusted public keys.

**Private read**: this is trickier if anyone has physical access to the files. Here I was thinking of encrypting database objects with public/private keys like PGP email security. How to manage groups though? Like PGP we could create a random key to encrypt each database object, and then encrypt that with each user in the access group's public key, attached to the DB object. That would make group membership difficult to manage: every object would need to have a new key added if we added a new user. The second option would be a keystore in the DB of keys for each access group which are used to encrypt objects, and each group key is encrypted with each user in the group's public key. The security issue here is that any user could decrypt the key and share it, and give access to all the objects to anyone else, but this is the same as passwords. Changing the keys would be very difficult though: ever object would need to be re-encrypted in every copy of the database. 

Indexing would be an issue, but a local synced copy of the database would not necessarily need to be encrypted in the same way: it could store an unencrypted version of everything the user has access to within an encrypted volume and index locally.

The ultimate aim of this is a security model that would work without a central server with security through encryption when everyone potentially has access to the data being shared. Have others been thinking about this and tried to implement something similar?

When I say database I am thinking about static CSV/JSON files, git stores, leveldb disk stores, and couchDB amongst others.

I should add that I am not a security expert in any way and I am new to all this, so please excuse any incorrectly used terminology or concepts.

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat. Solving this problem is definitely on our to do list, but we are currently focused on the open data use case for the time being. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
