### ISSUE TITLE
Idea: dat as a data retrieval tool 

### ISSUE THREAD

**Issue by dimazest** [maxogden/dat#64]
The idea is rather vague and high-level, I would like to discuss it with you.

Almost all scientific experiments require input data. Consider a script that counts words in a large collection of text. In the example below the [SWDA](http://compprag.christopherpotts.net/swda.html) is used:

``` bash
$ count-words --corpus /PATH_TO_SWDA/
100000
```

However, it's responsibility of the user to 

* obtain the corpus
* put it in the right place
* make sure that the corpus files are not changed

To solve the issues, it would be nice to have the following interface:

``` bash
$ count-words --corpus dat://some.domain/SWDA
100000
```
Then I expect that the files are 
* pulled from the server in case they absent
* the integrity is checked

Under the hood, I would expect that the files of  [swda](http://compprag.christopherpotts.net/code-data/swda.zip) are put somewhere, so the script could access them.

Is it something `dat` could support? Are there other tools that solve the issue?

**Comment by karissa** [comment]
We should really have a way to `dat install` or `dat get` other dats. related to #298

**Comment by karissa** [comment]
Thanks for your input, this will probably be handled by an external module. I started working on this: http://github.com/karissa/dps
