### ISSUE TITLE
Synchronization

### ISSUE THREAD

**Issue by tomasdev** [maxogden/dat#7]
(It might be related with #5) I'm having some doubts about sync and it may be because this is just starting and I don't know much. :smile: 

From `README`:
> `dat` will provide a pluggable API for synchronization so that plugins can be written to export and import remote data efficiently from existing databases.

1. Should we define sync before, after or at the same time than defining transformations?
2. How can we `dat`ize a project which we don't own. This is probably going to be a common case considering N sources.
3. How should it behave for non versioning databases?
4. Considering pagination and no source versioning, how can we know old rows had had an update?
5. Considering no pagination and no source versioning, will it have to "download" the complete source thing to know what changed?
6. Either way, (off 3, 4 and 5) how will we define the "pluggability" of the API that `dat` will provide.

**Comment by joehand** [comment]
Most of this discussion was around previous versions of dat. Dat 1.0 is much better for syncing!
