### ISSUE TITLE
Dataset licensing metadata

### ISSUE THREAD

**Issue by jden** [maxogden/dat#9]
Given that a big part of the use case for `dat` is enabling easier use, re-mixing, and re-use of the data, it would be great to bake in a convention for declaring data licensing in a machine readable way, similar to node's `package.json`'s `license` property. Hopefully this will allow both for greater opportunities for data discovery and also create more awareness around licensing issues from both the publisher and consumer end. In `npm` for example, there is a great community convention around using liberal software licensing like bsd or mit. For non-technical communities, a great example is Flickr, which has long supported adding Creative Commons metadata to photos at upload time and to their advanced search query builder.

/cc @vthunder

**Comment by karissa** [comment]
I think we can close this, we have a package.json now in `dat` and people can add a license to that (i.e., npm).
