### ISSUE TITLE
try and guess what format input data is

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#92]
doing e.g. `dat import foo.csv` right now doesn't work, it will complain that you didn't specify the format so you have to do `dat import foo.csv --csv` instead

it'd be nice if we did something sensible like this:

- if you don't specify the format explicity:
- then try and guess the format based on 'peeking' at the first chunk of data
- if you can't guess based on peeking then use the incoming file extension (e.g. .csv)

to implement the 'peeking' we need some code to detect newline separated JSON, CSV, multibuffer, protobuf and JSON objects (non newline e.g. pretty printed, related to https://github.com/maxogden/dat/issues/37)

also maybe it should prompt the user for a y/n if we guess the format

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat. Would you mind trying out the new dat with `npm install -g dat`? You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
