### ISSUE TITLE
persistent replication API

### ISSUE THREAD

**Issue by maxogden** [maxogden/dat#95]
right now doing `pull` and `push` are one time actions. we should have a replication API for 'registering' remotes + actions to take on those remotes: re syncing

e.g. `dat subscribe foo.com` would be kind of equal to `dat pull --save --live foo.com` where the `--save` means 'persist this remote', and `--live` will make dat automatically re-connect the live pull whenever it is running

we could also register remotes that aren't live updating, which would be useful for e.g. listing all remotes in a UI later on so that users can issue one-off pulls. we should also think about replicating the remotes along with the data (so that when you clone a dat you get it's remotes too)

**Comment by karissa** [comment]
Still love this idea!

**Comment by karissa** [comment]
I think this is doable in 1.0 -- we already are almost all the way there. 

I'd propose concretely:

`dat changes --live`

and

allowing `hooks: push` and `hooks: pull` in the package.json file.
