### ISSUE TITLE
`select` subsets of the data

### ISSUE THREAD

**Issue by jbenet** [maxogden/dat#97]
Would be awesome be able to `select` in the UI. Meaning, grab a subset of the columns and/or subset of the rows (based on functions, like ranges). And the `select` should be in the url. like `#some-query`. I started thinking about this selector-like thing in `datadex`, see: https://github.com/jbenet/data/blob/master/dev/formats.md#selecting

This should probably be the same for the cli (`dat cat <select>`, `dat pull http://foo.bar/#<select>`)

**Comment by karissa** [comment]
I think we are going to leave out any complex querying in dat, but now we have datasets, and there is a proposal for filtering datasets on dat export here: #286
