### ISSUE TITLE
MQTT -> dat

### ISSUE THREAD

**Issue by mcollina** [maxogden/dat#98]
I'm thinking of a MQTT to dat thing to allow streaming data from MQTT-enabled devices to dat users. MQTT can be added to Arduinos and other types of HW (including smartphones) and it works very well even with spotty connections.

You can get a nice intro to MQTT at these interactive slides (http://mcollina.github.io/mqtt_and_nodejs/ on Chrome) or at this talk https://www.youtube.com/watch?v=WE7GVIFRV7Q.

You can find a test broker at test.mosca.io.

I think there are two ways for adding this functionality:

1. as a command line tool
2. as a separate dat endpoint

## command line tool

MQTT supports a nice feature called 'offline messaging', which allows a client to receive all the message published while it was offline. A command line tool can then use that feature and dump it into dat, not losing any messages if the connection crashes. The only trick is storing the MQTT `clientId` into the .dat folder.

I'm not sure if this should be separate CLI that uses dat internally or should be a contribution to dat itself.

## separate dat endpoint

I think it is possible to expose http://dat.mosca.io/my/topic to allow 'dat pull' all the data published at the given topic to the current dat.
However, I'm not completely sure how to expose a streaming dat repository (i.e. I do not want to store anything on the server).

The mqtt->dat endpoint will use the same offline functionality as before, so no messages will be lost.

------

What do you think?

**Comment by karissa** [comment]
Hey, sorry for the late nudge. I think you could do this by implementing an alternative backend for dat (all data just gets stored in a given leveldown, but this is experimental. see the [COOKBOOK!](https://github.com/maxogden/dat/blob/master/docs/cookbook.md)) or subscribing to a `dat pull`. Are you still working on this problem?

**Comment by karissa** [comment]
After a whole year of feedback from the community, we recently published a new version of dat. Would you mind trying out the new dat with `npm install -g dat` and see if it still works for your use case? In the meantime, I'm going to close this issue. You can read about the new dat [announcement on the website](http://dat-data.com/blog/2016-02-01-dat-1) and [how it works in the docs](https://github.com/datproject/docs/blob/master/how-dat-works.md).
